cucumber/common

SUMMARY.md, docs/gherkin.md
Scenario Outline section is taken from https://github.com/cucumber/cucumber/wiki/Scenario-Outlines and pages 74-75 of The Cucumber Book.
=> Adding Scenario Outline section to Gherkin page and updating tag on SUMMARY.md

SUMMARY.md, docs/techniques.md
=> DOC: Small edit to summary.md page to link to three amigos content

html-formatter/nodejs/.eslintrc.yml, html-formatter/nodejs/lib/build_app.js, html-formatter/nodejs/lib/build_web_app.js, html-formatter/nodejs/lib/common/reducer.js, html-formatter/nodejs/lib/html_stream.jsx, html-formatter/nodejs/lib/react/html_formatter_app.jsx, html-formatter/nodejs/lib/socket_server.js, html-formatter/nodejs/package.json, html-formatter/nodejs/test/common/reducer_test.js, html-formatter/nodejs/test/cucumber_react/cucumber_react_test.js, html-formatter/nodejs/test/event_source_stream.js, html-formatter/nodejs/test/html_stream_test.js, html-formatter/nodejs/test/reducer_stream_test.js, html-formatter/nodejs/webpack.config.js
This PR sets up [ESLint](http://eslint.org/) for html-formatter
=> [html-formatter] Use ESLint

cucumber-expressions/javascript/README.md, cucumber-expressions/javascript/index.js
@aslakhellesoy 
Same as #76 but for cucumber expressions
=> [cucumber-expressions] make require-able and add example

cucumber-expressions/CHANGELOG.md, cucumber-expressions/javascript/src/transform.js, cucumber-expressions/javascript/test/custom_transform_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/transform.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_transform_spec.rb
=> Regexp literals in transforms. Fixes #109.

event-protocol/schemas/attachment.json, event-protocol/schemas/defs.json, event-protocol/schemas/source.json, event-protocol/schemas/start.json
This just makes the schemas a bit easier to read and comprehend
=> event-protocol: Tidy up schema titles and add descriptions

gherkin/python/setup.py
=> gherkin-python: Fix for #153

docs/10-minute-tutorial.md
This PR makes the text more uniform, by ending sentences.
- add an exclamation mark
- add a colon
The documentation's introductory tutorial needs polish to get out of the way and do its job.
I have not done any testing, BUT this tutorial stops short of using its ten minutes with the reader. Is it meant to be complete like this? Should it end with a) more text of its own? b) a link to the next content to read? or c) something else?
~(Is there a way of running Gitbook locally?)~ See `docs/contributing-to-documentation.md`.
=> [docs] 10-minute-tutorial: Format text

gherkin/ruby/.travis.yml
=> gherkin: Update CI matrix

docs/gherkin.md
GitHub requires a space after the hashmark.
Adding a space after the hashmark fixes this issue.
To make it more readable on GitHub.
Checked that on GitHub.
=> [docs] Fix markdown format for GitHub

docs/architecture/writing-a-new-cucumber.md
Fix broken links to close issue #92
=> Fix broken links (issue #92)

tag-expressions/java/src/main/java/io/cucumber/tagexpressions/TagExpressionParser.java, tag-expressions/java/src/test/java/io/cucumber/tagexpressions/TagExpressionParserParameterizedTest.java, tag-expressions/java/src/test/java/io/cucumber/tagexpressions/TagExpressionParserTest.java, tag-expressions/javascript/lib/tag_expression_parser.js, tag-expressions/javascript/test/tag_expression_parser_test.js, tag-expressions/ruby/lib/cucumber/tag_expressions/expressions.rb, tag-expressions/ruby/lib/cucumber/tag_expressions/parser.rb, tag-expressions/ruby/spec/expressions_spec.rb, tag-expressions/ruby/spec/parser_spec.rb
escape (, ), \ when they are contained in tags' name in tag expressions
=> Tag expressions: escape special chars in tags

tag-expressions/java/pom.xml
=> tag-expressions: Fix OSGI exported package

gherkin/java/CONTRIBUTING.md
The CONTRIBUTING.md wasn't clear on how to contribute.
I updated the reference to the CONTRIBUTING.md that was missing. It pointed towards an old file in cucumber/gherkin.
The repository to clone was cucumber/gherkin which is obsolete. I changed it to say cucumber/cucumber instead.
The documentation confused me when I wanted to share another pull request. I thought I better update the documentation when I noticed the problem.
I have done manual testing to verify that the updated links ends up where I expected them to end up.
=> gherkin java: Improved contributing documentation

cucumber-expressions/java/.gitrepo, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionPatternTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/javascript/.gitrepo, cucumber-expressions/javascript/test/cucumber_expression_test.js, cucumber-expressions/javascript/test/tree_regexp_test.js, cucumber-expressions/ruby/.gitrepo, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
=> Cucumber expressions regression 323

gherkin/gherkin-languages.json
Added aragonese language, "an" in ISO 639-1, to gherkin-languages.
https://en.wikipedia.org/wiki/Aragonese_language
=> added aragonese to gherkin supported languages

CONTRIBUTING.md
trivial: Corrected spelling from "agains" to "against"
This was a trivial fix for a spelling mistake in the contributing doc.
Just changed "agains" to "against"
This change just cleans up the documentation.
No code was changed.
=> Fixed a trivial spelling error on contributing.md

docs/living-documentation.md
=> Spelling fix

docs/cucumber.md
While reading the docs, I made typo, grammar, and formatting changes, for improved readability.
I'd also like to note that mentioning a beginner would have a first question, then give two questions, is confusing. Additionally, the answer to how Cucumber works with BDD being answered with another question is even more confusing. 
is this the latest documentation? 
- *NA* I've added tests for my code.
=> Updates cucumber.md type:docs

gherkin/c/gherkin-languages.json
Quick PR after following this tweet:  https://twitter.com/cucumberbdd/status/981766556584763397
=> 🇩🇪 Improve German translation

cucumber-expressions/go/regular_expression_test.go
=> fix cucumber-expressions tests

tag-expressions/javascript/README.md
=> tag-expressions: Fix doc link

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/cucumber_expression.go, cucumber-expressions/go/cucumber_expression_generator.go, cucumber-expressions/go/cucumber_expression_generator_test.go, cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpressionGenerator.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/src/cucumber_expression_generator.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/javascript/test/cucumber_expression_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression_generator.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
=> Allow escaping of '/'. Closes #391

Makefile, gherkin/perl/CHANGES
resolves #343 
Using BASH_SOURCE wasn't working when the shell wasn't bash.
Includes the additional change of syncing the gherkin changelog.
=> fix CI process: rsync

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/javascript/src/parameter_type.js, cucumber-expressions/javascript/src/parameter_type_registry.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_registry.rb
=> Fix for #404

scripts/functions.sh
Trying to figure out why monorepo non-master branches sometimes get pushed to subrepos' master branch.
=> [WIP] Splitsh branching

gherkin/go/README.md, gherkin/go/astbuilder.go, gherkin/go/cli/main.go, gherkin/go/dialects_builtin.go, gherkin/go/gherkin-generate-tokens/gherkin-generate-tokens.go, gherkin/go/gherkin.go, gherkin/go/gherkin_messages.go, gherkin/go/gherkin_messages_test.go, gherkin/go/matcher.go, gherkin/go/pickles.go
* Fix some formatting issues with gofmt -s
* Add godoc and goreportcard badges to README
Summary is enough 
Add a direct link to godoc and add goreportcard which is a useful tool to check quickly various quality metrics in a go project.
No tests required for those changes
=> gherkin-go: Fix some formatting issues, add useful badges

gherkin/go/astbuilder.go, gherkin/go/gherkin.go, gherkin/go/matcher.go, gherkin/go/parser.go, gherkin/go/parser.go.razor
=> Change underscore notation to camel case

cucumber-expressions/javascript/src/tree_regexp.js, cucumber-expressions/javascript/test/regular_expression_test.js, cucumber-expressions/javascript/test/tree_regexp_test.js
Javascript implemention for bugfix. See: https://github.com/cucumber/cucumber/pull/461
- [-] New feature (non-breaking change which adds functionality).
- [-] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
=> cucumber-expressisons: parenthesis character class (javascript)

cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/tree_regexp.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/tree_regexp_spec.rb
Ruby implemention for bugfix. See: #461
=> cucumber-expressions-ruby:parenthesis character class (ruby)

gherkin/gherkin-languages.json
"Ukoliko" expresses the givens for the test linguistically in more natural way.
=> Ads "Ukoliko" as Croatian "Given" alternative

tag-expressions/python/MANIFEST.in
Minimal change, needed for source-package creation.
FIX "MANIFEST.in" for source-distribution package creation.
- Add LICENSE (was: missing)
- Add Makefile (was: missing)
- Add "scripts" subdir (was: missing)
NOTE: Used when you run "python setup.py sdist".
Fix an omission in the source-package creation process.
Provides now a complete source distribution of the project.
NOTE: Nothing above applies (or is needed).
=> tag-expressions.python: FIX MANIFEST.in for source-distribution package creation

cucumber-messages/messages.proto
Supersedes #501
Lets make sure we agree on the protobuf updates before rolling it out to the implementations.
=> add cucumber engine message

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ExpressionFactory.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ExpressionFactoryTest.java
=> Better expression heuristics. Closes #515.

gherkin/dotnet/Gherkin/Gherkin.csproj
Update Version number to 6.0.0-beta1
Be able to make a pre-release
Tried in SpecFlow
=> [Gherkin-DotNet] update version number to 6.0.0-beta1

datatable/java/datatable/pom.xml, datatable/java/dependencies/pom.xml, datatable/java/pom.xml
=> datatable - Upgrade jackson databind

HACKING.md, tag-expressions/CHANGELOG.md, tag-expressions/go/README.md, tag-expressions/java/README.md, tag-expressions/python/README.md, tag-expressions/python/README.rst, tag-expressions/python/cucumber_tag_expressions/__init__.py, tag-expressions/ruby/README.md, tag-expressions/ruby/cucumber-tag_expressions.gemspec
Closes #560 - Fixes up documentation links across code-base
=> Fix up documentation links for tag-expressions

gherkin/dotnet/Gherkin/Gherkin.csproj
To be able to make a final SpecFlow 3 Release, we have to release the current Gherkin- Package not as prerelease.
This PR removes the pre-release tag from the version.
Final SpecFlow 3 release
=> [Gherkin-DotNet] update version number to 6.0.0

gherkin/gherkin-languages.json
```gherkin
Feature: Add more keyword aliases
In order to engage algorithmically illiterate people
As a gherkin runner
I want to provide the idiomatic keywords they use
```
This commit is untested, but the words are already loved and used in our features by our non-technical people.
Poetry?
> Are there tests for each language ?
=> I18N French: Add "Sachant que" as Given, and "Donc" as Then

datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java
Default datatable transformers are not converting empty cell to null but throwing exception instead.
e.g.
io.cucumber.datatable.CucumberDataTableException: 'java.util.List<java.util.List<java.lang.Double>>' could not transform
Fixed for all types but String as its a breaking change and separate PR will be raised for v5
Empty cell should be converted to `null` by default for nullable number types (`Double`, `Float`, `Int` etc.). So that the table in the following step 
Then the marker values are
| M1   | 1.7988 |
| M2   |        |
| M3   | 1.5312 |
| M4   | 1.7720 |
| M5   | 1.6840 |
| M6   | 0.0000 |
| M9   |        |
| M12 | 1.7002 |
is transformed to
{
"M1": 1.7988,
"M2": null,
"M3": 1.5312,
"M4": 1.7720,
"M5": 1.6840,
"M6": 0.0,
"M9": null,
"M12": 1.7002,
}
The empty cell is not …
=> Fixes cucumber/cucumber-jvm#1617 (cucumber-jwm) empty cells conversion

Makefile
See https://github.com/cucumber/cucumber/pull/619
=> Remove failing dots formatter from build

cucumber-expressions/CHANGELOG.md, cucumber-expressions/java/pom.xml, datatable/CHANGELOG.md, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableType.java
Update changelogs, bump dependency versions, deprecate code.
=> Post release maintaince

gherkin/gherkin-languages.json
Fix correct translation keyword in Portuguese and Spanish
=> Adding Rule keyword translation in portuguese and spanish

.templates/default.mk, c21e/default.mk, config/default.mk, cucumber-expressions/default.mk, cucumber-messages/CHANGELOG.md, cucumber-messages/default.mk, cucumber-messages/messages.md, cucumber-messages/messages.proto, datatable/default.mk, dots-formatter/default.mk, gherkin/default.mk, tag-expressions/default.mk
See issue #665 - I just added the documentation generation
=> Techtalk update test run finished message with timestamp

datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistryTableConverter.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/UndefinedDataTableTypeException.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java
Fixes: https://github.com/cucumber/cucumber/issues/537
=> datatable: Improve handling of tables withouth header

.templates/dotnet/default.mk, c21e/javascript/package.json, cucumber-expressions/javascript/package.json, cucumber-messages/dotnet/default.mk, cucumber-messages/javascript/package.json, cucumber-react/javascript/package.json, datatable/java/pom.xml, dots-formatter/go/go.mod, dots-formatter/go/go.sum, fake-cucumber/javascript/package.json, gherkin/javascript/package.json, html-formatter/javascript/package.json, tag-expressions/javascript/package.json
Update external dependencies (`make update-dependencies`)
=> Update dependencies 2019 08 29

tag-expressions/go/parser_test.go
Refactor tests for tag expressions (go).
This PR refactors existing tests for tag expressions (go) using [table driven approach](https://github.com/golang/go/wiki/TableDrivenTests).
=> tag-expressions-go: Refactor tests

gherkin/gherkin-languages.json
=>  Better Indonesian Translation 

tag-expressions/go/parser.go
Refactor `tokenize` function of tag expressions parser (go).
Refactor `tokenize` function of GO tag expressions parser to make it more readable and easy to follow. The behavior remains intact.
=> tag-expressions-go: Refactor tokenize function

cucumber-expressions/go/go.mod
=> cucumber-expressions-go: Fix go.mod

c21e/javascript/package.json, cucumber-demo-formatter/go/go.mod, cucumber-demo-formatter/go/go.sum, cucumber-expressions/javascript/package.json, cucumber-messages/java/pom.xml, cucumber-messages/javascript/package.json, cucumber-query/javascript/package.json, cucumber-query/javascript/src/CucumberQuery.ts, cucumber-react/javascript/package.json, fake-cucumber/javascript/package.json, fake-cucumber/javascript/test/CucumberTest.ts, gherkin/go/go.mod, gherkin/go/go.sum, gherkin/java/pom.xml, gherkin/javascript/package.json, html-formatter/javascript/package.json, json-formatter/go/go.mod, json-formatter/go/go.sum, tag-expressions/javascript/package.json
Add some more checks to Cucumber-Query. And update dependencies.
=> Improve Cucumber-Query. Update dependencies

datatable/java/datatable/src/main/java/io/cucumber/datatable/CucumberDataTableException.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java
Fix typo
Fix typo in error message.
Update test accordingly.
Ran the unit tests related to this class. As I am at work , I'm not able to build the entire project atm.
Java change only(?)
=> datatable: Fix typo in error message and test

gherkin/java/src/main/java/io/cucumber/gherkin/GherkinDocumentBuilder.java, gherkin/java/src/main/java/io/cucumber/gherkin/GherkinLine.java, gherkin/java/src/main/java/io/cucumber/gherkin/ParserException.java, gherkin/java/src/main/java/io/cucumber/gherkin/StringUtils.java, gherkin/java/src/main/java/io/cucumber/gherkin/TokenFormatter.java
We're using Java 8 so we can remove these redundant string util
=> gherkin: Remove redundant string util

.circleci/config.yml, cucumber-expressions/CHANGELOG.md, cucumber-expressions/javascript/package.json, cucumber-expressions/javascript/src/ParameterTypeMatcher.ts
(Reapplies #841 which had to be pulled out due to a botched merge by me)
=> cucumber-expressions: remove node 8 support

gherkin/README.md
=> gherkin: Fix broken links

messages/CHANGELOG.md, messages/go/time_conversion_test.go, messages/java/src/test/java/io/cucumber/messages/TimeConversionTest.java, messages/javascript/test/TimeConversionTest.ts, messages/ruby/lib/cucumber/messages/time_conversion.rb, messages/ruby/spec/cucumber/messages/time_conversion_spec.rb
Fixes some errors in the maths
=> Fix time conversion bugs

json-to-messages/javascript/Makefile
Should fix #961
Issue can be reproduced easily:
```shell
cd json-to-messages
make clean
cd javascript
make
```
=> Do not hang when trying to compute all.ndjson in json-to-messages.

json-to-messages/CHANGELOG.md, json-to-messages/Makefile, json-to-messages/javascript/package.json, json-to-messages/javascript/src/PredictableHook.ts, json-to-messages/javascript/src/PredictableStepDefinition.ts, json-to-messages/javascript/src/PredictableSupportCode.ts, json-to-messages/javascript/src/PredictableTestSteps.ts, json-to-messages/javascript/src/SupportCodeExecutor.ts, json-to-messages/javascript/src/test-generation/makePredictablePickleTestStep.ts, json-to-messages/javascript/test/PredictableHookTest.ts, json-to-messages/javascript/test/PredictableSupportCodeTest.ts, json-to-messages/javascript/test/PredictableTestStepsTest.ts, json-to-messages/javascript/test/test-generation/makePredictableHookTestStepTest.ts, json-to-messages/javascript/test/test-generation/makePredictablePickleTestStepTest.ts
The `package.json` file was not pointing to the mono-repo version but to 10.0.
Thi fixes it and also do the upgrade to v12
=> Update messages in json to messages

json-to-messages/CHANGELOG.md, json-to-messages/javascript/src/stream/JSONTransformStream.ts, json-to-messages/javascript/test/stream/JSONTransformStreamTest.ts
=> Catch JSON parsing errors in json-to-messages

query/README.md
Fixed small typo in readme.
Removed an `s`.
The documentation should be error free :-)
Not necessary.
=> cucumber-query: Update README.md

Dockerfile
JAVA_HOME Environment variable added to the release Dockerfile
The release Dockerfile does not include the JAVA_HOME Environment variable.  This forces someone doing a release to set the variable in their local environment via `export JAVA_HOME=?`.  
This sets the JAVA_HOME for Ubuntu in the Dockerfile so that it is not necessary for the user to set it in their local environment before building and running the container. 
- [ X ] New feature (non-breaking change which adds functionality).
=> Cucumber: Fixed #1049 by adding JAVA_HOME to Dockerfile

react/javascript/src/components/gherkin/Step.tsx
=> react/javascript: Do not use clickable links for parameters

create-meta/java/pom.xml, datatable/java/datatable/pom.xml, gherkin/java/pom.xml, messages/java/pom.xml
Fixes: https://github.com/cucumber/cucumber/issues/1090
=> build: Fix maven-shade warnings

gherkin/CHANGELOG.md, gherkin/javascript/src/Errors.ts, gherkin/javascript/test/TokenMatcherTest.ts
=> gherkin/javascript: Throw NoSuchLanguageException when language is unknown

gherkin/ruby/README.md
I am not really sure if this is the right target, but the old target is not helpful at all.
=> Update the link to Gherkin

CONTRIBUTING_NEW.md
When reading `CONTRIBUTING_NEW` initially, I did not understand what `PACKAGES` and `LANGUAGES` were. This small PR tries to help with that. 
Now that I know what `PACKAGES` and `LANGUAGES` are, it seems obvious, but I think making it clear can help newcomers.
=> Add some information about how packages and languages are mapped

messages/CHANGELOG.md, messages/dotnet/messages.proto, messages/go/messages.proto, messages/java/messages.proto, messages/javascript/messages.proto, messages/messages.proto, messages/ruby/messages.proto
This is a partial fix for #997
=> Add Attachment#url

.circleci/config.yml
Right now Elixir messages library isn't checked with CircleCI. With this PR it will / should be checked.
=> Elixir messages circleci

messages/elixir/.gitignore, messages/elixir/Makefile, messages/elixir/mix.lock
Add `mix.lock` and update the `Makefile` so that builds no longer fail.
=> Include mix.lock in messages/elixir

gherkin/Makefile, gherkin/perl/.gitignore, gherkin/perl/Makefile
Add gherkin-perl to the CI build as discussed in the weekly update meeting.
=> [gherkin-perl] Include Perl in CI build

gherkin/CHANGELOG.md
As pointed out by @mpkorstanje, my name should be at the bottom of CHANGELOG.md for gherkin.
Add my name and GitHub profile link.
=> gherkin: Mention @ehuelsmann in CHANGELOG.md

fake-cucumber/javascript/src/cli.ts, gherkin/CHANGELOG.md, gherkin/javascript/src/IGherkinOptions.ts, gherkin/javascript/src/cli/main.ts, gherkin/javascript/src/stream/GherkinStreams.ts, gherkin/javascript/test/StreamTest.ts, react/javascript/test/acceptanceTests.tsx, react/javascript/test/hidePassedScenariosTest.ts
=> Remove IGherkinOptions#createReadStream. Fixes #1284

.templates/go/default.mk, cucumber-expressions/go/default.mk, demo-formatter/go/default.mk, gherkin/CHANGELOG.md, gherkin/go/default.mk, json-formatter/go/default.mk, messages/go/default.mk, tag-expressions/go/default.mk
Fix for #1347 
Also see https://cucumberbdd.slack.com/archives/C62D0FK0E/p1612780385133700?thread_ts=1612455059.095000&cid=C62D0FK0E
=> Fix building of MacOS (darwin) executables

gherkin/CHANGELOG.md, gherkin/c/gherkin-languages.json, gherkin/dotnet/Gherkin/gherkin-languages.json, gherkin/elixir/priv/gherkin_languages.json, gherkin/gherkin-languages.json, gherkin/go/gherkin-languages.json, gherkin/java/src/main/resources/io/cucumber/gherkin/gherkin-languages.json, gherkin/javascript/src/gherkin-languages.json, gherkin/objective-c/GherkinLanguages/gherkin-languages.json, gherkin/perl/gherkin-languages.json, gherkin/python/gherkin/gherkin-languages.json, gherkin/ruby/lib/gherkin/gherkin-languages.json
Set the proper Hungarian keyword for `Rule`, it was set to the English version, so this is non-breaking.
=> Set Hungarian rule keyword

gherkin/CHANGELOG.md
Added berp upgrade to gherkin v19.0.2 changelog
=> Add berp upgrade to gherkin v19.0.2 changelog

gherkin/CHANGELOG.md, messages/CHANGELOG.md
=> Update CHANGELOG.md following json-schema messages

gherkin-streams/javascript/README.md
=> gherkin: fix documentation for @cucumber/gherkin-streams

messages/README.md, messages/java/README.md, messages/java/pom.xml, messages/javascript/README.md, messages/javascript/package.json, messages/ruby/README.md
- Remove mentions of protocol buffers from core language modules
- Correct first cucumber-js version to add support
=> correct some bits of documentation for messages

.circleci/config.yml, tag-expressions/python/Makefile
Use cimg/python rather than circleci/python
circleci/python:3.9.6 seems to have been updated recently and python2 seems not to be available anymore.
It is part of cimg/python.
`cimg` images aims to supercede legacy `circleci` ones as explain here: https://circleci.com/developer/images/image/cimg/python#image-name
=> Use newer cimg/python image for CI

.templates/javascript-esm/default.mk, .templates/javascript/default.mk, compatibility-kit/javascript/default.mk, create-meta/javascript/default.mk, fake-cucumber/javascript/default.mk, gherkin-streams/javascript/default.mk, gherkin-utils/javascript/default.mk, gherkin/javascript/default.mk, html-formatter/javascript/default.mk, json-formatter/javascript-testdata/default.mk, json-to-messages/javascript-testdata/default.mk, json-to-messages/javascript/default.mk, language-server/javascript/default.mk, language-service/javascript/default.mk, message-streams/javascript/default.mk, messages/javascript/default.mk, monaco/javascript/default.mk, package.json, query/javascript/default.mk, react/javascript/default.mk, suggest/javascript/default.mk, tag-expressions/javascript/default.mk, vscode/javascript/default.mk
There are still some difficulties during the release process.
Those modification should help to fix the issues we may encounter by properly installing the javascript modules before trying to use them
=> Fix release process by fixing javascript makefiles

.templates/perl/default.mk, gherkin/perl/default.mk, messages/perl/.github/ISSUE_TEMPLATE.md, messages/perl/.github/PULL_REQUEST_TEMPLATE.md, messages/perl/.rsync, messages/perl/Makefile, messages/perl/default.mk
Fix the issue with  `make clean` with perl I guess?
@ehuelsmann ^
=> Perl less dzil

gherkin/php/composer.json
The post-release script must have an error in it :/ it's only meant to add new minor versions
=> Gherkin PHP - Fix messages constraint

messages/CHANGELOG.md, messages/javascript/package.json
https://github.com/cucumber/common/pull/2010 has added the schemas within the "javascript" folder, but they are still not part of the npm package
=> [Messages][Javascript] Add schema to npm packages

tsconfig.build.json
This adds the `inlineSources` setting in `tsconfig` (see https://www.typescriptlang.org/tsconfig#inlineSources)
Fixes #2039.
=> Set the inlineSources tsconfig setting to true

gherkin/java/README.md
=> java: Fix broken link in README.md

gherkin-utils/CHANGELOG.md, gherkin-utils/javascript/package.json
`package.json` seems to have a wrong entry for `bin` option.
Fixes #2051
=> gherkin/javascript: fix package.json bin has a wrong entry for gherkin-utils
