cucumber/common

cucumber-expressions/README.md
`22` should have been `42` in `cucumber-expressions/README.md`
=> Fixed typo

SUMMARY.md, docs/installation.md
Using installation instructions from the https://cucumber.io/docs#installation pages to add Javascript and Ruby instructions. Adding some structure to the installation part of the SUMMARY.md menu.
=> DOC: Installation page additions

tag-expressions/javascript/README.md, tag-expressions/javascript/index.js
Integrated this with a feature branch and would like some updates. Currently you cannot do `require('cucumber-tag-expressions')` because it does not have an `index.js` in the project directory or a `main` file specificed in the `package.json` 
This adds `index.js` to the javascript module so it can be required.  You can then access the `TagExpressionParser` property on the result.
Currently `require('cucumber-tag-expressions')` throws cannot find module.
Using `require('cucumber-tag-expressions/lib/tag_expression_parser')` feels wrong and likely to break
This type of file isn't typically tested. I added it manually to my installed node module locally and it was working
=> update javascript cucumber-tag-expressions

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpressionGenerator.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/GeneratedExpression.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/javascript/lib/cucumber_expression_generator.js, cucumber-expressions/javascript/lib/generated_expression.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/javascript/test/custom_transform_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression_generator.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/generated_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb
@aslakhellesoy 
resolves #82 
I think cucumber-expressions needs it own repo similar to gherkin so there is a single CI build to test everything.
=> [cucumber-expressions] generated expressions - expose argument names

cucumber-expressions/examples.txt, cucumber-expressions/java/examples.txt, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ConstructorTransform.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ConstructorTransformTest.java, cucumber-expressions/javascript/examples.txt, cucumber-expressions/ruby/examples.txt
To be able to handle optional groups in regexp, null should be transformed to null.
[Java] When performing a constructor transform on the value null, the transformed object should also be null.
To be able to use cucumber-expressions in Cucumber-JVM optional groups in regexps ([like this](https://github.com/cucumber/cucumber-jvm/blob/master/jruby/src/test/resources/cucumber/runtime/jrubytest/stepdefs.rb#L33-L35)) need to be handled. Currently the Java implementation throws a "Failed to invoke `new String("null")`" instead.
=> [cucumber-expressions] handle optional groups in regexp.

cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/test/cucumber_expression_regexp_test.js, cucumber-expressions/javascript/test/custom_transform_test.js
When creating a new transform with multiple capture group regexps, cucumber fail to match expressions that are not using the first capturing regexp.
For instance, a transform with the captureGroupRegexps with the value ['red', 'yellow'] would fail to match an expression containing yellow.
The matching expression is now a disjonction of all the capturing regexps using non capturing group (with `(?:...)`).
I had an issue when using multiple regexps for the same transform as it was only matching the first one. This commit fix it.
I added one test that use the second regexp of the `captureGroupRegexps` option of a transform (and that is not matching a subset of the first regexp).
=> [cucumber-expressions] Handle multiple capture group regexps for matching

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpressionGenerator.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/javascript/src/cucumber_expression_generator.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression_generator.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/generated_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb
This PR generates untyped CucumberExpression snippets
Untyped parameters in a CucumberExpression become typed if their name match a registered type.
In other words, the type name can always be used as a parameter name. This improves the readability of a CucumberExpression.
This fixes #110
=> cucumber-expressions: Untyped GeneratedExpression

cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/test/cucumber_expression_test.js
resolves #103 
Only the JS for now. After initial review, I'll update the java / ruby versions
=> cucumber-expressions: replace special characters

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterRegistry.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionPatternTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CustomParameterTest.java, cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/src/parameter_registry.js, cucumber-expressions/javascript/test/cucumber_expression_regexp_test.js, cucumber-expressions/javascript/test/cucumber_expression_test.js, cucumber-expressions/javascript/test/custom_parameter_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_registry.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_regexp_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_parameter_spec.rb
After having used Cucumber expressions daily for a few weeks I have realised that:
* The `{name:type}` syntax is usually redundant for both built-in and custom parameters (previously called transforms, see #114)
*The `{name:type}` syntax is never needed, not even for expressions with multiple parameters of the same type. It is sufficient to give different names to the function/method parameters of the stepdef. 
* The `{name:type}` syntax is ugly and causes more visual/cognitive strain
So let's get rid of it! This PR prints a deprecation warning with a recommendation to `STDERR` if the `{name:type}` syntax is used. In a future release we can remove support for it altogether.
=> Deprecate {name:type} syntax in favoud of just {type}

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/Argument.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ArgumentBuilder.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CustomParameterTest.java, cucumber-expressions/javascript/src/argument.js, cucumber-expressions/javascript/src/build_arguments.js, cucumber-expressions/javascript/test/custom_parameter_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/argument.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/argument_builder.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_parameter_spec.rb
Fix for #118 
Inject `Parameter` into `Argument` so that transformation can be deferred. 
Cucumber needs to match expressions without performing a transform. See cucumber/cucumber-js#765
=> Defer parameter transformation until after the match

cucumber-expressions/java/pom.xml, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterRegistry.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CustomParameterTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/RegularExpressionTest.java, cucumber-expressions/javascript/src/parameter_registry.js, cucumber-expressions/javascript/test/assert_throws.js, cucumber-expressions/javascript/test/custom_parameter_test.js, cucumber-expressions/javascript/test/regular_expression_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_registry.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_parameter_spec.rb
The main reason for this is better UX for end users: They'll get better error messages and stricter rules for defining new parameter types. This should help catch a whole class of errors when a parameter type is defined rather than when a step has ambiguous matches.
=> Detect conflicts before a new parameter is added

event-protocol/schemas/attachment.json, event-protocol/schemas/defs.json, event-protocol/schemas/source.json, event-protocol/schemas/start.json, event-protocol/validate.js
In JSON schemas, you can [use refs to other files to re-use parts of your schema](https://code.tutsplus.com/tutorials/validating-data-with-json-schema-part-2--cms-25640). This PR demonstrates how it can be done, though it doesn't do it everywhere yet.
I extracted the definitions for the `timestamp` and `series` properties into a separate `defs.json` file and referenced that.
I also cleaned up the validate.js code a bit, based on some examples I was reading about using `ajv`.
As the schema grows, we need to be able to easily maintain it. Keeping duplication down will be important in this.
I ran `make` and everything is still green.
=> event-protocol: Use $ref to reduce duplication in schemas

event-protocol/schemas/attachment.json, event-protocol/schemas/defs.json
This will make it easier to add other events that use a location.
I've added the uri so you *can* specify the file if you need to, otherwise we can infer the uri from the parent.
=> event-protocol: extract location schema ref

cucumber-expressions/CHANGELOG.md, cucumber-expressions/README.md, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionPatternTest.java, cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/test/cucumber_expression_regexp_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_regexp_spec.rb
Implement alternative text, inspired from [turnip alternative words](https://github.com/jnicklas/turnip#placeholders).
=> cucumber-expressions: Add support for alternative text

event-protocol/README.md
Bring docs for event-protocol up to date with result of IRL discussions between @mattwynne, @aslakhellesoy and @jbpros.
=> event-protocol: document decisions from meetup

gherkin/python/gherkin-python.razor, gherkin/python/gherkin/parser.py, gherkin/python/gherkin/stream/gherkin_events.py, gherkin/python/gherkin/stream/source_events.py
Fix #138 'gherkin: Fix build on python 3.4'
The first fix was to extract the message from the exception in a way that works in both Python 2 and Python 3 (`str(error)`).
This reviled that on Python 3 the newline encodings was not preserved (the [datatable.feature](https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/datatables.feature#L5) contains a few lines the use `\r\n` as newline/line ending). To fix I had to make changes in how the files are read into the source events, which includes reading them into unicode strings. This rippled to some changes in the Parser since Python 2 differentiate between strings, `str`, and unicode-strings, `unicode`, (which both are subtypes to `basestring`), whereas Python 3 tread both string and unicode-strings as `str`. 
Make Gherkin …
=> gherkin: (Python) Fix handling of error messages and newline encodings

gherkin/perl/dist.ini
Fix meta information
This changes the `[MetaResources]` section in `dist.ini` to point to the official issue tracker. It points the repository to the `cucumber/gherkin-perl` subrepo mirror.
We want users and contributors to use the official issue tracker and repos.
=> gherkin-perl: Change MetaResources to point to official location

gherkin/ruby/.travis.yml
I want to add  ruby-head to Travis as a allow failures for `gherkin-ruby`.
The motivation and the detail is same with cucumber/cucumber-ruby#1087
When I send this PR here, below Travis will test my `.travis.yml` right?
https://travis-ci.org/cucumber/gherkin-ruby
=> [gherkin-ruby] Add ruby-head as a allow failures in .travis.yml.

event-protocol/bin/cucumber-event-validator.js
I might have missed something, but I couldn't work out to run it (from
another directory) anymore since it moved into the bin directory in
3dbafa2e4a327a4251038a97063b7de5e0da3f88
=> event-protocol: Make binary command executable and add hashbang

gherkin/go/cli/main.go, gherkin/go/events.go
Adds error handling as discussed in previous PR
`gherkin.GherkinEvents(paths ...string)` now returns a list of events and an unexpected error.
The error might be due to:
- failure to open feature file for reading
- unexpected gherkin token
- unexpected gherkin parser error
The **cli** exits with status code **1** in case of such error and prints it to **stderr**, errors expected from parser are interpreted as events.
=> gherkin-go: missing error handling

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java, cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb
Remove support for `{foo:int}` style parameters
We realised a couple of releases back that parameters only need to name its type. The name can be set to whatever the user wants in the associated method/function's parameters.
We still have 100% coverage
=> cucumber-expressions: Remove named params (already deprecated)

tag-expressions/java/pom.xml
Build the tag-expressions jar as a OSGi bundle.
* Declare the packaging type as `bundle`
* Use the `maven-bundle-plugin` to create the manifest according to the OSGi requirement.
cucumber/cucumber-jvm#873 added support to execute Cucumber-JVM in OSGi containers. To not lose that ability when using the tag-expression library in Cucumber-JVM, the tag-expressions jar need to be built as an OSGi bundle.
I have locally run the [pax-exam example of Cucumber-JVM](https://github.com/cucumber/cucumber-jvm/tree/master/examples/pax-exam), which exemplifies testing OSGi bundles, successfully with these changes.
=> tag-expressions: (Java) Make the jar a bundle to support osgi.

SUMMARY.md
This PR edits the docs.cucumber.io site's _menu_ on the left-hand side of the screen to **visibly include PHP** and spell JavaScript with that casing.
=> [docs] Spell out JavaScript, make PHP (Behat) visible

CODE_OF_CONDUCT.md
- this fixes Markdown formatting in the output to make two headings render as Markdown
- [ci skip]
=> Markdown fix: avoid non-space character

gherkin-lint/README.md
Fixes a link to the Github Issues filter that appears in the README.md.
The label name has apparently been changed and the link references the old label name.
I followed [this link](https://docs.cucumber.io/gherkin-lint/#) and it took me to a list with no issues in it.
=> gherkin-lint: Fix link in README.md

docs/contributing-to-documentation.md
This PR adds a link to Slack to the docs on how to contribute to documentation.
=> [docs] Add Slack link to Gitbook docs on contributions

docs/contributing-to-documentation.md
Summary: 
All documentation updates should be in the new docs.cucumber.io repository
Details: 
This PR is part of https://github.com/cucumber/docs.cucumber.io/issues/15
=> [docs] Add note and link to docs.cucumber.io

cucumber-expressions/CHANGELOG.md, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/GroupBuilder.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/RegularExpression.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/RegularExpressionTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/TreeRegexpTest.java, cucumber-expressions/javascript/src/group_builder.js, cucumber-expressions/javascript/src/regular_expression.js, cucumber-expressions/javascript/src/tree_regexp.js, cucumber-expressions/javascript/test/regular_expression_test.js, cucumber-expressions/javascript/test/tree_regexp_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/group_builder.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/regular_expression.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/tree_regexp.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/regular_expression_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/tree_regexp_spec.rb
Fix how regexps are parsed
See #253 for a description of the problem. This is an alternative implementation which leverages the existing regexp parser in `TreeRegexp`, which means consistency and reliability (compared to parsing regexp with regexp).
=> Cucumber expressions fix regexp parsing

tag-expressions/ruby/.travis.yml
This change updates the Rubies to latest generally available versions.
This does the same as #256 does.
=> tag-expressions: Update CI matrix

cucumber-expressions/ruby/.travis.yml
This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rbenv/ruby-build/tree/master/share/ruby-build
- See https://github.com/cucumber/cucumber-expressions-ruby/pull/1/
=> cucumber-expressions: Update CI matrix

cucumber-expressions/CHANGELOG.md, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpressionGenerator.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/javascript/src/cucumber_expression_generator.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression_generator.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb
This is a fix for #276. Escaping all `%` signs as `%%` before `sprintf` / `String.format` / `util.format` fixes this.
=> Cucumber expressions 276 escape string template

gherkin/README.md
Change image link in gherkin README to correct location for the ast class diagram picture.
Old link refers to a non existing picture. When browsing to https://github.com/cucumber/cucumber/tree/master/gherkin no picture is shown in the AST section.
Did the change in my fork and browsed to it at https://github.com/elrisco/cucumber/tree/master/gherkin and saw the picture.
- [ x] Bug fix (non-breaking change which fixes an issue).
=> gherkin: Correct link to ast picture in README

gherkin/gherkin-languages.json
Added missing female, singular for 'Given' in Romanian supported by a native Romanian speaker (Bianca at Mozaic Works)
=> Gherkin: Added female, singular 'Given' in Romanian

cucumber-expressions/CHANGELOG.md, cucumber-expressions/README.md, cucumber-expressions/javascript/src/argument.js, cucumber-expressions/javascript/src/parameter_type.js, cucumber-expressions/javascript/test/cucumber_expression_test.js, cucumber-expressions/javascript/test/custom_parameter_type_test.js, cucumber-expressions/javascript/test/expression_examples_test.js, cucumber-expressions/javascript/test/regular_expression_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/argument.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_parameter_type_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/expression_examples_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/regular_expression_spec.rb
Run `transformer` in the context of the World.
`transformer` functions often need access to the World in order to transform an object.
Unit tests
=> Cucumber expressions run in world

README.md
I'm not sure if there's a subrepo for the readme - it doesn't seem like it. Let me know if I should rename this PR.
I propose using the Wikipedia entry on BDD for the currently dead-end link in the readme.
Fixes https://github.com/cucumber/cucumber/issues/44
Clicked the link in the readme and verified it goes to wikipedia ;)
=> Docs/Readme - Add wikipedia link for BDD

gherkin/c/.gitrepo, gherkin/c/Makefile, gherkin/java/gherkin-java.razor, gherkin/java/src/main/java/gherkin/Parser.java, gherkin/java/src/main/java/gherkin/TokenMatcher.java, gherkin/java/src/main/java/gherkin/events/Events.java, gherkin/java/src/test/java/gherkin/events/EventsTest.java, gherkin/javascript/lib/gherkin/generate_events.js, gherkin/javascript/lib/gherkin/parser.js, gherkin/javascript/lib/gherkin/stream/event_stream.js, gherkin/javascript/test/stream/event_stream_test.js, gherkin/javascript/test/stream/test_fr.feature, gherkin/ruby/lib/gherkin/stream/gherkin_events.rb, gherkin/ruby/lib/gherkin/stream/source_events.rb, gherkin/ruby/spec/gherkin/stream/gherkin_events_spec.rb, gherkin/ruby/spec/gherkin/stream/test_fr.feature
Updating a couple gherkin APIs to accept a language parameter
* Allowing a language to be passed into `generateEvents` and `EventStream`
* Update `Parser.parse` to pass the second parameter to be passed through to the `TokenMatcher` to avoid having to create a `TokenMatcher` in `generateEvents`
Attempting to resolve this issue: https://github.com/cucumber/cucumber-js/issues/929
Added a new test to event_stream. This tests all the changes and
=> gherkin: add language parameter to API

cucumber-expressions/java/pom.xml
Build the cucumber-expressions jar as a OSGi bundle.
See also #99.
* Declare the packaging type as bundle
* Use the maven-bundle-plugin to create the manifest according to the OSGi requirement.
cucumber/cucumber-jvm#873 added support to execute Cucumber-JVM in OSGi containers. To not lose that ability when using the cucumber-expression library in Cucumber-JVM, the cucumber-expressions jar need to be built as an OSGi bundle.
I have locally run the pax-exam example of Cucumber-JVM, which exemplifies testing OSGi bundles, successfully with these changes.
=> cucumber-expressions: (Java) Make the jar a bundle to support osgi.

tag-expressions/ruby/bin/cucumber-tag-expressions
Command-line tool that prints the location of scenarios matching a certain tag expression
The tool reads a Cucumber event stream (produced by the `gherkin` command line tool) from `STDIN` and prints the locations (in "rerun.txt" format) to `STDOUT`
This tool can be used as a preprocessor before running `cucumber` to get a list of scenarios to execute before running `cucumber`.
While `cucumber` can filter scenarios with the `--tags` option, it is sometimes useful to perform this filtering before running `cucumber` so that several `cucumber` processes can be spawned in parallel.
This can speed up the execution for slow scenarios.
Manually
When multiple `cucumber` processes are run in parallel, each process will produce an independent report. These reports will have to be combined in order …
=> Experimental CLI for tag expressions

gherkin/java/pom.xml
mockito, hamcrest and other testing libraries typically provide an
*-all version that also contains their dependencies. This may lead
to class path conflicts. This can be avoided by importing the
indivudual core libraries.
In this case not required as mockito isn't used.
=> gherkin java: Remove unused mockito-all dependency

cucumber-expressions/README.md, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
This allows parentheses to be explicitly escaped in cucumber expressions, so that they can be interpreted literally. This addresses issue #333.
I changed `OPTIONAL_REGEXP` so that it looks for an optional escape character before the opening parenthesis. If found, the subsequent `gsub` will emit escaped parentheses, rather than the optional group.
It was necessary to look for a _double_-escaped parenthesis, though, because of how the `ESCAPE_REGEXP` was already escaping special characters.
The motivation is described in #333, but to summarize in brief, I am using Cucumber to describe an API in a platform-agnostic manner, for a book I am writing. I am using the Cucumber scenarios to describe function calls, which enclose parameter lists in parentheses. The cucumber expressions were not …
=> cucumber-expressions: Allow parentheses to be explicitly escaped

gherkin/python/gherkin-python.razor, gherkin/python/gherkin/parser.py
=> Fixes #335

cucumber-expressions/README.md, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java
* Renames bigint -> biginteger
* Replaces INTEGER_REGEXPS  -> FLOAT_REGEXPS for bigdecimal
* Enables snippet generation for bytes
https://github.com/cucumber/cucumber-jvm/pull/1248
=> Fix default Java parameter types

tag-expressions/python/README.md, tag-expressions/python/README.rst, tag-expressions/python/tasks/release.py
README tweaks to publish python package on https://pypi.org
* Adapt "README.rst" for package registration on new https://pypi.org
with Cucumber logo and badges
* Correct link to tag-expression docs:
https://docs.cucumber.io/cucumber/api/#tag-expressions
(was: http://docs.cucumber.io/tag-expressions/ ; now missing)
OTHERWISE:
* Add note about currently required work-around to publish
new release packages on https://pypi.org
Not applicable, text-only w/ correction of broken URLs in documentation.
=> tag-expressions-python: README TWEAKS

Dockerfile.cucumber-build-dotnet
Together with https://github.com/cucumber/gherkin-dotnet/pull/15 it should fix the .NET build on the monorepo.
Only merge when https://github.com/cucumber/gherkin-dotnet/pull/15 is pulled into monorepo.
Use latest version of .NET Core SDK as of now (2.1.105)
To fix the build
I run the tests locally in docker.
Docker image have to be regenerated and pushed to docker hub.
=> Use latest .NET Core SDK in DotNet docker image

datatable/README.md, datatable/java/README.md, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTable.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableType.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/UndefinedDataTableTypeException.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java
Provide a simple (one-liner) to convert a data table to a list of objects:
```java
registry.defineDataTableType(DataTableType.entry(Author.class))
```
Also provide a simple (one-liner) to convert a cell into a "string wrapper" value object:
```java
registry.defineDataTableType(DataTableType.cell(AirportCode.class))
```
* `entry` uses Jackson Databind's `ObjectMapper` to convert a table entry (`Map<String,String>`) into an object.
* `cell` uses reflection to call a String constructor.
Cucumber-JVM 2 used to convert tables to `List<Something>` automatically, with zero configuration. Version 3 removed XStream and added a more flexible conversion API, but some users have reported this as a regression (in ease of use). They now need to write more code to do something that used to be automatic. …
=> datatable: Automatic list conversion

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/cucumber_expression.go, cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/go/custom_parameter_type_test.go, cucumber-expressions/go/parameter_type.go, cucumber-expressions/go/parameter_type_registry.go, cucumber-expressions/go/regular_expression.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpression.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/RegularExpression.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CustomParameterTypeTest.java, cucumber-expressions/javascript/src/cucumber_expression.js, cucumber-expressions/javascript/src/parameter_type.js, cucumber-expressions/javascript/src/parameter_type_registry.js, cucumber-expressions/javascript/src/regular_expression.js, cucumber-expressions/javascript/test/cucumber_expression_test.js, cucumber-expressions/javascript/test/custom_parameter_type_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_registry.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/regular_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/custom_parameter_type_spec.rb
Fix for #387. Also allows registration of parameter types without a name (useful if only used in conjunction with regular expressions)
=> Cucumber expressions no special characters in parameter types

cucumber-expressions/ruby/spec/coverage.rb
This PR changes the code coverage counting in the Ruby sub-project to **only count non-spec files**.
The motivation for this is **clarity and understandability** of the code **coverage report** to its reader.
I only re-ran the tests, to have a new coverage HTML report generated.
Non-functional change to reporting.
=> cucumber-expressions/ruby: Exclude spec/ from coverage counting

cucumber-expressions/CHANGELOG.md, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/EnumParameterTypeTest.java
Simplify creation of `ParameterType` from an enum class
The enum constants' names are used to build a regexp for the match (`red|green|blue`), and the name is the simplified name of the enum class (`Color`).
See https://github.com/cucumber/cucumber-jvm/issues/1393#issuecomment-400985459
=> Add ParameterType.fromEnum(Class enumClass)

HACKING.md, config/java/README.md, gherkin-lint/javascript/README.md, html-formatter/nodejs/README.md, tag-expressions/java/README.md, tag-expressions/ruby/README.md, tag-expressions/ruby/cucumber-tag_expressions.gemspec
There were a few broken links, this PR fixes them. Gherkin-lint does not have docs yet [docs-issue#215](https://github.com/cucumber/docs.cucumber.io/issues/215).
Fixes issue #450, although Event Protocol does not seem to be in docs as mentioned in the issue.
=> Fix links to docs site.

cucumber-expressions/java/examples.txt, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ExpressionExamplesTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/TreeRegexpTest.java
- fix {word}-expression using Unicode characters.
- fix line separator in ExpressionExamplesTest.
I think the summary is detailed enough :)
I have a problem when using {word}-expression with russian words. 
I've written unit-tests. An I'm testing it in my bdd-project. 
- [x ] Bug fix (non-breaking change which fixes an issue).
- [ x] I've added tests for my code.
=> cucumber-expressions: {word}-expression with unicode fix

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ExpressionFactory.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ExpressionFactoryTest.java
fix optional text expression using Unicode characters.
I think the summary is detailed enough :)
I have a problem when using optional text expression with russian words.
I've written unit-tests. And I'm testing it in my bdd-project.
- [x ] Bug fix (non-breaking change which fixes an issue).
- [ x] I've added tests for my code.
=> cucumber-expressions:  optional text with Unicode bugfix

tag-expressions/python/.bumpversion.cfg, tag-expressions/python/.gitignore, tag-expressions/python/.subrepo, tag-expressions/python/.travis.yml, tag-expressions/python/Pipfile, tag-expressions/python/README.md, tag-expressions/python/README.rst, tag-expressions/python/cucumber_tag_expressions/__init__.py, tag-expressions/python/cucumber_tag_expressions/parser.py, tag-expressions/python/invoke.yaml, tag-expressions/python/py.requirements/testing.txt, tag-expressions/python/pytest.ini, tag-expressions/python/setup.py, tag-expressions/python/tox.ini
Add basic support for #406 to be solved externally by providing overridable function as extension point.
In addition:
* Update to newest Python 3.7 and newer package versions.
* Fix URL to cucumber tag-expression docs in `README.md` (info was moved, already corrected on other  tag-expression implementations (Java, Javascript, ...).
With this change the functionality of feature request #406 can be solved externally.
A function was added that can serve as extension point to implement the desired functionality.
Test suite works (as before).
=> tag-expressions-python: Update and basic support for #406

tag-expressions/python/.bumpversion.cfg, tag-expressions/python/cucumber_tag_expressions/__init__.py, tag-expressions/python/pytest.ini, tag-expressions/python/setup.py
BUMP-VERSION: 1.1.2.dev0 (was: 1.1.1). 
Reenable development mode again.
After release post-processing to mark package version as in development mode.
Tox run w/ multiple Python versions.
=> tag-expressions.python: Bump version to 1.1.2.dev0 (was: 1.1.1)

tag-expressions/python/.subrepo
FIX Travis build that currently fails in step "scripts/push_subrepos.sh". 
Current Travis build fails in step "scripts/push_subrepos.sh":
```
...
28 commits created, 2210 commits traversed, in 1.005s
remote: Repository not found.
fatal: repository 'https://[secure]@github.com/cucumber/tag-expressions-python.git.git/' not found
The command "scripts/push_subrepos.sh" exited with 1.
...
```
FIX: Remove ".git" in file ".subrepo" again.
SAD: Can only be tested on Travis build (AFAIK).
=> tag-expressions.python: FIX: CI travis build: push_subrepos step

cucumber-messages/go/messages.proto, cucumber-messages/java/messages.proto, cucumber-messages/javascript/messages.proto, cucumber-messages/messages.proto, cucumber-messages/ruby/messages.proto
The TestCaseFinished message should have a testResult field.
Also the TestCaseFinished message should have a testResult field, not only the TestStepFinished.
Since the summary is printed:
```
xxx scenarios (x1 Passed, ...)
yyy steps (y1 Passed, ...)
```
the concept of test cases having result clearly exists. It should be the responsibility of the cucumber-engine to calculate that result, not each and every listener to the message stream. The cucumber-engine need to know the result of the test case (so far) anyway to be able to decide how to treat the next step (run, skip ...).
Still WIP
Is adding a field to a message a "new feature" or a "breaking change"?
=> cucumber-messages: Add testResult to the TestCaseFinished message

datatable/CHANGELOG.md, datatable/README.md, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistryTableConverter.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java
In some scenarios default converters would be used when a defined
converter was available. This was caused by returning a default
converter as soon as no regular converter was available.
This heuristic works well with two exceptions:
* When the table contains a single line the default table entry
transformer is never applicable
* When the table keys don't imply a table entry the default table
entry transformer is never applicable
By inlining this lookup and working out the exceptions the
old behaviour is restored.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1489
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1490
=> datatables: Fix priority of default converters

gherkin/c/src/gherkin_line.c
Leading Tab characters is kept in the trimmed_line and
GherkinLine_start_with can't recognize keywords in this case
If a feature file uses Tab character for indentation then the parser build incorrect AST: nothing keywords will not be detected in the text with indentation.
I'v modified GherkinLine_new to remove leading Tab characters in the trimmed_line field as well as whitespaces.
Our editor allows to use Tab characters. In this case we had invalid AST.
=> Leading Tab characters break parser logic

cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/NumberParserTest.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/NumberParserTest.java
Fix locale for number parsers
Obvious mistake. Failure went unnoticed because the core repo always fails.
=> Fix locale for number parsers

cucumber-messages/ruby/Gemfile, cucumber-messages/ruby/cucumber-messages.gemspec
There is no Java release of google-protobuf version 3.6.1. The latest working Java version seems to be 3.2.0.2. Allow JRuby users to select this older version by loosening the dependency on google-protobuf.
Loosens the gem dependency as declared in the gemspec.
Builds with Cucumber 4.0.0.rc.1 currently fail on JRuby because no compatible version of google-protobuf can be installed.
I ran the specs and installed `cucumber-messages` locally on JRuby with the older `google-protobuf` version (3.2.0.2). I then was able to ~run Cucumber scenarios with~ install cucumber 4.0.0.rc.1 under JRuby.
- Bug fix (non-breaking change which fixes an issue).
=> cucumber-messages: Allow compatible version of google-protobuf with JRuby

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/combinatorial_generated_expression_factory.go, cucumber-expressions/go/cucumber_expression_generator_test.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CombinatorialGeneratedExpressionFactory.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/javascript/src/combinatorial_generated_expression_factory.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/ruby/.gitignore, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/combinatorial_generated_expression_factory.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb
Using only small input values it is possible make
`CucumberExpressionGenerator` generate 1.5GB worth of generated
expressions.
For example: the step `a simple step` -a total of 11 letters- and 4
parameters with a the regular expression of [a-z] will generate a
4^11=419430 possible cucumber expressions. As each GeneratedExpression
takes up approximately 11*32 bytes this totals just shy of 1.5GB.
While this can be avoided by not using parameter types with overly
generic expressions for snippet generation, snippet generation is
enabled by default and once we run out memory it is impossible to
inform or warn anyone about this problem.
So 256 cucumber expressions should be enough for anyone.
Fixes: #574
=> cucumber-expressions: limit explosion of generated expressions to 256

cucumber-messages/CHANGELOG.md, cucumber-messages/ruby/Gemfile, cucumber-messages/ruby/cucumber-messages.gemspec
As the comments elude to; this gem is a key runtime dependency. And on Ruby 2.6 this only works when using the latest version
Stricter gemspec restrictions as per the different ruby requirements
For Running on JRuby and a couple of other environments, a weaker requirement is required (And not the latest), due to some issues with those environments.
Once the team maintaining this has done some additional work, we can probably relax this requirement. But for now this makes cucumber build properly again X-Ruby Versions
=> cucumber-messages: Add stricter gem restrictions for google-protobuf

cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
When using Integers captured using the {int} cucumber expression, issues crop up when trying to sanitize the brackets which are being read as an optional parameter.
The issue is occurring due to interoperability between brackets being partially escapable (To represent these are brackets and not a capture group), and cucumber expressions (Which have a different meaning for brackets)
I've allowed brackets to be used in a very specific context (As notified by the constant definition), when being used inside a Cucumber Expression Generator method (Which would previously crash erroneously)
Fixes Ruby issue #1337 https://github.com/cucumber/cucumber-ruby/issues/1337
This code is likely to need porting and is only meant as a first draft. It's probably going to need some stern eyes to work out if …
=> Fix ruby issue 1337: Brackets/Integer/CukeExp compatibility

cucumber-expressions/go/cucumber_expression_generator_test.go, cucumber-expressions/go/parameter_type_matcher.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/CucumberExpressionGenerator.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeMatcher.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/NumberParserTest.java, cucumber-expressions/javascript/src/parameter_type_matcher.js, cucumber-expressions/javascript/test/cucumber_expression_generator_test.js, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_matcher.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_generator_spec.rb
Given `a simple step` and a parameter type that matches zero or more
characters `[a-z]*` and a parameter type that matches exactly one
character `[a-z]` two expressions will be generated. Neither very useful.
```
{exactly-one} {exactly-one}{zero-or-more} {exactly-one}{zero-or-more}
{zero-or-more} {exactly-one}{zero-or-more} {exactly-one}{zero-or-more}
```
This result is generated because after advancing `ParameterTypeMatcher`
to just after `a` the zero-or-more expression will match the empty
string between `a` and the following space. The `exactly-one-expression`
will proceed and match the first character after that space.
By advancing `ParameterTypeMatcher` until a non empty match is
found we can avoid expressions that match the empty string from getting
stuck.
This will generate:
``` …
```
=> cucumber-expressions: Prefer expression with the longest non-empty match

gherkin/c/CMakeLists.txt
Allow the user to specify whether they want a static or dynamic library.
The `SHARED` in the call of `add_library` has been removed.
Not everyone wants to have a dynamic `gherkin-c` library, it should be the users choice whether they need a static or a dynamic build. For that purpose CMake provides the variable `BUILD_SHARED_LIBS` to be set by the user. However, explicitly specifying a SHARED or STATIC library build in `add_library` causes this setting to be ignored. Thus by removing the `SHARED` in `add_library` the users can now choose themselves.
I built the library locally using 
`cmake -DBUILD_SHARED_LIBS=ON -Bbuild -H. && cmake --build build`
and using `cmake -DBUILD_SHARED_LIBS=OFF -Bbuild -H. && cmake --build build`
with cmake 3.13.1 on linux.
=> gherkin-c: Allow user to choose between static and dynamic lib

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformer.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformerTest.java
Converting to Boolean was supported by default in older cucumber version. 
This PR restores it.
Boolean is a basic type and supporting it will ease the upgrade of cucumber from previous versions
Unit tests + manual checks
=> cucumber-expressions: Support Boolean in BuiltInParameterTransformer

Makefile
Remove failing dots formatter from build
```
bundle exec rspec --color
F
Failures:
1) Cucumber::Formatter::Dots prints coloured dots
Failure/Error: @stdin, stdout, _stderr, @wait_thread = Open3.popen3(@exe)
Errno::ENOENT:
No such file or directory - /app/dots-formatter/ruby/dots-formatter-go/dots-formatter-go-linux-amd64
Finished in 0.00531 seconds (files took 0.20413 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/cucumber/formatter/dots_spec.rb:36 # Cucumber::Formatter::Dots prints coloured dots
```
=> Remove failing dots formatter from build

HACKING.md
Provide a quick note to show people how to run docker in the HACKING.md file.
=> Add quick note about running Docker [ci skip]

c21e/java/.travis.yml, config/java/.travis.yml, cucumber-expressions/java/.travis.yml, cucumber-messages/java/.travis.yml, datatable/java/.travis.yml, gherkin/java/.travis.yml, tag-expressions/java/.travis.yml
OracleJDK 8 is no longer provided as a Unix package and no longer
available as part of Travis CI.
=> Replace OracleJDK with OpenJDK

scripts/functions.sh
`md5sum` is not installed by default on a Mac, and using `md5` avoids the need to further filter the output
Mac users should be able to use the docker build without installing tools locally
=> docker config: Use `md5` rather than `md5sum`

c21e/javascript/src/ExeFile.ts, c21e/javascript/test/ExeFileTest.ts, gherkin/javascript/src/index.ts
Imports the default export `ExeFile` from c21e in a way that doesn't result in an undefined constructor.
fixes https://github.com/cucumber/cucumber/issues/634
Will add tests, if necessary for a trivial change like that, once established that this is the fix we want: https://github.com/cucumber/cucumber/issues/634#issuecomment-502896358
=> gherkin: fix: ExeFile not a constructor, issue #634

cucumber-expressions/java/heuristics.adoc, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ExpressionFactory.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ExpressionFactoryTest.java
Explaining when a string is interpreted as a cucumber expression should
be rather straight forward. In essence the explanation should be:
If you surround a string with `^` and `$` it will be a regular
expression. If not, it is a cucumber expression.
However the heuristic complicates this by checking if a capture group
contains regular expression symbols `[]+.*` with the assumption that
these are not used in normal writing.
This allows us to write little marvels like:
this looks\( i.e: no regex symbols) like a cukexp
a heavy storm forecast \(BF {int}+)
the temperature is (\+){int} degrees celsius
Which look deceptively like cucumber expressions but are in fact regular
expressions. Simplifying the heuristic remove this ambiguity. This does
comes at the cost of being able to recognize …
=> cucumber-expressions: Simplify java heuristic

tag-expressions/python/.bumpversion.cfg, tag-expressions/python/DEVELOPMENT.rst, tag-expressions/python/cucumber_tag_expressions/__init__.py, tag-expressions/python/cucumber_tag_expressions/parser.py, tag-expressions/python/invoke.yaml, tag-expressions/python/pytest.ini, tag-expressions/python/setup.py, tag-expressions/python/tasks/__init__.py, tag-expressions/python/tasks/_tasklet_cleanup.py, tag-expressions/python/tasks/py.requirements.txt, tag-expressions/python/tests/unit/test_parser.py, tag-expressions/python/tox.ini
Removes a DeprecationWarning while using python3.7 (or newer) when running the tests.
* Primary issue above (minor issue in docstring)
* BUMP-VERSION: 1.1.2 (was: 1.1.2.dev0)
* Additional cleanups (invoke, tox.ini)
Removes the annoying DeprecationWarning when tests are run with python3.
Using the test suite.
Only python implementation of tag-expressions is affected.
=> tag-expressions (python): Fix python3 warning

cucumber-messages/messages.proto
Add timestamp property to TestRunFinished message so that we know when the TestRun is finished.
Do I need to update all messages.proto files in the repo or only that one and that is synced in the build?
=> Add Timestamp property and comments to TestRunFinished message

cucumber-messages/ruby/Gemfile, cucumber-messages/ruby/cucumber-messages.gemspec
Allow protobuf 3.8
This allows 3.8, which "should" fix all builds aside from JRuby (According to their maintainers). JRuby is something which isn't fully on their roadmap yet, so we're still on our own for that.
Should fix any niggling issues with 2.3-2.6 (Note that 3.8 forces Ruby 2.3, but we're already doing that)
CI
=> Allow google-protobuf 3.8

cucumber-expressions/go/cucumber_expression_regexp_test.go, cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/go/parameter_type_registry.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionPatternTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/NumberParserTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ParameterTypeRegistryTest.java, cucumber-expressions/javascript/src/ParameterTypeRegistry.ts, cucumber-expressions/javascript/test/CucumberExpressionRegExpTest.ts, cucumber-expressions/javascript/test/CucumberExpressionTest.ts, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_registry.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_regexp_spec.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
Different languages provided different degrees of support for number
parsing. Additionally when confronted with invalid input they also deal
this differently. Tailoring the regex to match the capabilities of the
language specific parser avoids nasty surprises later on.
Assumes number has been parsed when encountering unknown tokens
- Java
- JavaScript
- Ruby
Throws exception when encountering unknown tokens
- Go
Supports thousands separator
- Java
Supports scientific notation
- Java
- JavaScript
- Ruby
Supports positive exponential in scientific notation
- JavaScript
- Ruby
Closes: #675
=> cucumber-expressions: Tailor decimal pattern to number parser

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/combinatorial_generated_expression_factory_test.go, cucumber-expressions/go/cucumber_expression_generator_test.go, cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/go/custom_parameter_type_test.go, cucumber-expressions/go/parameter_type.go, cucumber-expressions/go/parameter_type_registry.go, cucumber-expressions/go/parameter_type_registry_test.go, cucumber-expressions/go/parameter_type_test.go, cucumber-expressions/go/regular_expression.go, cucumber-expressions/go/regular_expression_test.go, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformer.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/RegularExpression.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/RegularExpressionTest.java
When there is a conflict between the type hint from the regular expression
and the method prefer the the parameter type associated with the regular
expression. This ensures we will use the internal/user registered parameter
transformer rather then the default.
Unless the parameter type indicates it is the stronger type hint.
Reasoning:
1. Pure cucumber expression users will not notice this in either scenario.
2. Pure regular expression users will benefit because 
`BuiltInParameterTransformer` can now seamlessly transform any captured
values. (For all built in types `useRegexpMatchAsStrongTypeHint` is
explicitly set to false.)
2. Regular expression users that define a default transformer have little
need to define parameter types. The default transformer should be
sufficiently powerful to …
=> cucumber-expressions: Prefer Java type hint over parameter type

scripts/prepare_release_env.sh
Checks if the `prepare_release_env.sh` is executed in the docker container. Prevents the script from overwriting important information (ssh keys, gem credentials, ect).
=> build: Check if prepare release is done in docker

gherkin/gherkin-languages.json
Revived and enhanced PR #352 (solves #707).
"Szenariogrundriss" literally means "scenario floor plan" while it's meant to be a translation for "scenario outline". This in fact prevented me from using the the German translation at all, because I cannot make myself type this...
Sidenote: it seems that - from a user perspective - "scenario" and "scenario outline" could very well be merged in a single keyword, the distinction is probably only there to simplify parsing, but for a human reader it doesn't really matter.
Sidenote 2: if it's supported to include punctation in keywords, "Angenommen, " would be better than "Angenommen ", because no one writes a space before a comma (and we need a comma here).
For all keywords, I kept the originally provided translations to be sure not to break …
=> Improved German keywords

Dockerfile, gherkin/perl/Makefile
Add Perl infrastructure required to start testing Perl implementation.
Before this change, there's insufficient Perl in the images
(none, actually) to run the Perl tests and thus to verify
validity of PR #694.
Incidentally add `--notest` flag to cpanm to stop it from
downloading half of CPAN in order to test *dependencies* it's
building.
In my local Docker environment I verified that this change is enough to run Perl and install dependencies using the module installer `cpanm` on which the gherkin-perl Makefile depends.
None of the above are applicable.
=> gherkin-perl: Add Perl infrastructure to the CI docker images

.templates/java/default.mk, .templates/java/maven-versions-rules.xml, c21e/java/default.mk, c21e/java/maven-versions-rules.xml, config/java/default.mk, config/java/maven-versions-rules.xml, cucumber-expressions/java/default.mk, cucumber-expressions/java/maven-versions-rules.xml, cucumber-messages/java/default.mk, cucumber-messages/java/maven-versions-rules.xml, datatable/java/datatable/pom.xml, datatable/java/default.mk, datatable/java/maven-versions-rules.xml, datatable/java/pom.xml, gherkin/java/default.mk, gherkin/java/maven-versions-rules.xml, tag-expressions/java/default.mk, tag-expressions/java/maven-versions-rules.xml
During release process, ```mvn versions:use-latest-versions``` may pick non-final version (rc1 etc). 
This fixes it.
There's a new template file called ```maven-versions-rules.xml``` which specifies which releases to exclude when running ```use-latest-versions```.
Maybe this should go to cucumber-parent instead, so less files to manage.
Currently the list is pretty empty (tested with the ones that get picked when running ```use-latest-versions``` for datatable), it could be easily made bigger.
Avoid having to revert to final versions during the release process.
=> Do not update dependencies with non-final versions

c21e/javascript/package.json, cucumber-expressions/go/go.mod, cucumber-expressions/go/go.sum, cucumber-expressions/java/pom.xml, cucumber-expressions/javascript/package.json, cucumber-react/javascript/package.json, dots-formatter/go/go.mod, dots-formatter/go/go.sum, dots-formatter/ruby/cucumber-formatter-dots.gemspec, fake-cucumber/javascript/package.json, gherkin/go/go.sum, gherkin/java/pom.xml, gherkin/javascript/package.json, gherkin/ruby/gherkin.gemspec, html-formatter/javascript/package.json, json-formatter/go/go.sum, tag-expressions/go/go.mod, tag-expressions/go/go.sum, tag-expressions/javascript/package.json
Temporary PR: ran `make update-dependencies` at root level after release of `cucumber-messages`6.0.1, will be merged as soon as the CI is ok.
=> Update dependencies after release cucumber-message 6.0.1

cucumber-react/javascript/package.json, fake-cucumber/javascript/package.json, gherkin/go/go.mod, gherkin/go/go.sum
Temporary PR: ran make update-dependencies at root level after release of Gherkin 8.0, will be merged as soon as the CI is ok.
=> Update dependencies after release gherkin 8.0

.circleci/config.yml, cucumber-expressions/javascript/package.json, cucumber-expressions/javascript/src/ParameterTypeMatcher.ts
Updated CI to run cucumber-expressions against node 8, 10, 12. Currently did not update all other javascript libraries to do this, but it should be easy enough to do.
Resolves #725
The regular expression syntax being used is not supported on node 8. Found a library that provides the functionality. Used it and left a comment when we could remove its use (when node 8 reaches end of life).
cucumber-js wants to upgrade to latest cucumber-expressions but tries to support node 8, 10, 12.
Now running tests on node 8 and made updates to make this pass.
=> cucumber-expressions: support node 8

gherkin/javascript/src/external/GherkinExe.ts
In the process of trying to update cucumber-js to using gherkin 7.0.4, I ran into an issue where the go binary hit an error and it was hidden from me (the error was caused by passing it an invalid default language).
Updating stderr of the gherkin process to be inherited (ie redirected to the parent processes stderr), if the gherkin process hit some error, that will be visible to the calling process.
Docs on the stdio option: https://nodejs.org/api/child_process.html#child_process_options_stdio
Currently there is no indication the gherkin child process prints anything to stderr. By sending the gherkin child process stderr to the parent process stderr, the stderr is now visible and can be used to debug issues.
No tests currently, mainly something that should help in debugging.
=> gherkin: js external expose stderr

c21e/javascript/src/ExeFile.ts, c21e/javascript/test/ExeFileTest.ts
As part of updating cucumber-js to gherkin 7.0.4 (using the go binary), I'm hitting an issue when trying to run tests on appveyor (see screenshot)
Appears ia32 is not properly mapped to 386, the way x32 is.
Want to be able to use gherkin go binaries as part of gherkin js on win ia32.
Updated tests. Real test will be once this is released and no longer get this error on appveyor.
=> c21e: js fix for win-ia32

gherkin/README.md
cucumber/gherkin/README.md wrong C# example
Tuning issue
See [#736](https://github.com/cucumber/cucumber/issues/736)
I've adapted the C# example which describes how to use the Gherkin parser so that it works out of the box.
=> #736 Changed C# example within README.md

cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/javascript/src/Group.ts, cucumber-expressions/javascript/src/ParameterTypeRegistry.ts, cucumber-expressions/javascript/test/CucumberExpressionTest.ts, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
Changes to stop captures of empty string parameters being filtered off when interrogating the group, and to the specific transform function so that falsy values are handled
Added a small guard to the transform function for the "string" parameter type, so falsy values are switched for an empty string.
This was enough for the tests to pass, but at the root there was still the issue of this value being undefined, due to the logic in the getter for `children` in the `Group` class.
What `children` looks like when the string parameter is empty:
What children looks like when the string parameter is non-empty:
Best I can tell, the previous code used `value !== null` as the heuristic to filter off the first item; I've changed it to `start !== undefined`. Although to be fair it didn't seem to be …
=> cucumber-expressions: fix captured empty strings being undefined

tag-expressions/go/parser.go
Currently, we are saving token in a slice of rune and converting it to a string which is expensive. This PR replaces this with `bytes.Buffer` which is much faster.
**Before**
```
goos: darwin
goarch: amd64
expression: not a\\(\\) or b and not c or not d or e and f
BenchmarkTokenize-4   	  740218	      1571 ns/op
```
**After**
```
goos: darwin
goarch: amd64
expression: not a\\(\\) or b and not c or not d or e and f
BenchmarkTokenize-4   	 1227254	       978 ns/op
```
=> tag-expressions-go: Slice rune to string conversion is expensive

.templates/go/default.mk, cucumber-expressions/go/default.mk, cucumber-messages/go/default.mk, dots-formatter/go/default.mk, gherkin/go/default.mk, json-formatter/go/default.mk, pretty-formatter/go/default.mk, tag-expressions/go/default.mk
This should fix issue #774 that Aslak saw after releasing `cucumber-messages`. It does not try to update the `go.mod` file after release if the package does not use any other package in the mono-repo.
Don't break the `go.mod` file after releases.
Manually :/
Basically:
```shell
cd cucumber-messages/go # There is no dependencies for this package
make remove-replaces && make add-replaces
cd ../../gherkin/go
make remove-replaces && make add-replaces
```
Running `git status` should say everything is clean.
- [x] Build & ops
=> Release process: do not try to add replace in go.mod when there is no need (see #774)

HACKING.md
Take 3 :) This is a follow-on from #649 
NB: There are other links to travis in the HACKING.md file, but I don't know enough about this to fix it. So this is still needing to be updated. I've made an issue item about this to be tidied up
Update a few review points leftover that were added by aslak after previous PR was merged
=> Update docker hacking information

cucumber-expressions/javascript/package.json, cucumber-expressions/javascript/src/ParameterTypeMatcher.ts, cucumber-expressions/javascript/src/ParameterTypeRegistry.ts, cucumber-expressions/javascript/src/web.ts, cucumber-expressions/javascript/test/CucumberExpressionGeneratorTest.ts, cucumber-expressions/javascript/test/CucumberExpressionTest.ts, cucumber-expressions/javascript/test/TreeRegexpTest.ts, cucumber-expressions/javascript/webpack.config.js
I want to be able to pull in `cucumber-expressions` as a [jsDelivr](https://www.jsdelivr.com/) dependency (e.g. in a [Codepen](https://codepen.io/) pen).
What I want to create is a simple playground for Cucumber Expressions, similar to [rubular](https://rubular.com/) or [scriptular](https://scriptular.com/), but in a codepen we can embed in our docs.
This PR also ran code reformatting
=> Package cucumber-expressions with Webpack

cucumber-query/javascript/src/CucumberQuery.ts
Only look up `PickleStep` if a `TestStep` has a `pickleStepId` (it won't if it comes from a hook). 
Indirectly, via HTML Formatter
=> Only look up pickle step if test step has pickleStepId

.templates/java/scripts/check-jar.sh, c21e/java/scripts/check-jar.sh, config/java/scripts/check-jar.sh, cucumber-expressions/java/scripts/check-jar.sh, cucumber-messages/java/pom.xml, cucumber-messages/java/scripts/check-jar.sh, datatable/java/scripts/check-jar.sh, gherkin/java/pom.xml, gherkin/java/scripts/check-jar.sh, tag-expressions/java/scripts/check-jar.sh
Fixes incorrectly shaded dependencies and adds a script to ensure all classes are within the module path of the jar file.
`cucumber-message` did not relocate the `google.protobuf` package.
`gherkin` shaded the `cucumber-messages` dependency.
=> cucumber-messages/gherkin: Fix shaded dependencies

fake-cucumber/javascript/src/ITestStep.ts, fake-cucumber/javascript/src/IWorld.ts, fake-cucumber/javascript/src/SupportCodeExecutor.ts, fake-cucumber/javascript/src/TestCase.ts, fake-cucumber/javascript/src/TestStep.ts, fake-cucumber/javascript/src/makeDummyStepDefinitions.ts, fake-cucumber/javascript/test/HookTest.ts, fake-cucumber/javascript/test/StepDefinitionTest.ts, fake-cucumber/javascript/test/SupportCodeExecutorTest.ts, fake-cucumber/javascript/test/TestCaseTest.ts, fake-cucumber/javascript/test/TestPlanTest.ts, fake-cucumber/javascript/test/TestStepTest.ts, fake-cucumber/javascript/test/TestWorld.ts, json-formatter/go/json_elements.go, json-formatter/go/message_lookup.go, json-formatter/go/test_step.go, json-formatter/ruby/features/step_definitions/steps.rb, json-formatter/ruby/features/test_attachment.feature, json-formatter/ruby/features/test_basic.feature
This is the start of supporting attachments in the json formatter. It requires a change in fake cucumber to output attachment messages. The API is modelled after cucumber-js.
=> Json formatter attachments

cucumber-messages/dotnet/messages.proto, cucumber-messages/go/messages.proto, cucumber-messages/java/messages.proto, cucumber-messages/javascript/messages.proto, cucumber-messages/messages.proto, cucumber-messages/ruby/messages.proto
This follows-up #816, one of the field is still in camelCase.
Change `StepDefinition.sourceReference` to `StepDefinition.source_reference`
=> StepDefinition.sourceReference should be StepDefinition.source_reference

datatable/CHANGELOG.md, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/TypeFactory.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/TypeFactoryTest.java
When registering steps in Kotlin using Kotlin collections as an argument e.g:
```kotlin
@Given("orders with an order item and the following attributes:")
fun statusFilterOrdersInEs(attributes: Map<String, Map<String, String>>)
```
This argument is translated to Java type as
```java
Map<java.lang.String, ? extends java.util.Map<java.lang.String, java.lang.String>>
```
To handle this gracefully the simplified type system used by `DataTable`
should understand upper bounds. We do this by replacing the wild card type
with its upper bound.
We can assume this is safe because when registering a transformer to
`type ? extends SomeType` the transformer is guaranteed to produce an
object that is an instance of `SomeType`.
When transforming a data table to `? extends SomeType` a transformer that …
=> datatable: Replace wildcard type with its upper bound

gherkin/ruby/lib/gherkin/query.rb, gherkin/ruby/spec/gherkin/query_spec.rb
This was added in #845 as a fix until #848 would be merged. But in fact, the location for the `DocStrings` and `DataTable` arguments are not used.
=> Drop Gherkin::Query#argument_location which will not be useful

datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTable.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTest.java
DataTables are immutable. Changing the contents means they have to be
recreated. However it is not possible to recreate a data table and have
it use the same table converter as the original table.
Adding `DataTable.getTableConverter` makes this possible.
=> datatable/java: Add getter for TableConverter

tag-expressions/README.md
Fix broken links.  
Couldn't find the `standard-libary.adoc` anywhere. Seems to have been deleted a while ago. So I deleted that bit. We can always add it back once we get the Cucumber varieties thing going.
Fixes: #698
=> tag-expressions: Fix broken links

json-formatter/CHANGELOG.md, json-formatter/go/json.go, json-formatter/go/message_lookup.go, json-formatter/go/test_case.go, json-formatter/go/test_case_test.go, json-formatter/go/test_helpers.go, json-formatter/go/test_step.go, json-formatter/go/test_step_test.go
Fix the CCK for `cucumber-json-formatter`. This also replaces defensive programming with fail-fast.
=> Json formatter hooks

demo-formatter/README.md
Just fix a typo introduced when renaming `cucumber-demo-formatter` to `demo-formatter` in 97123062d.
=> demo-formatter: Fix demo-formatter folder name in example script

gherkin/CHANGELOG.md, gherkin/javascript/src/Gherkin.ts, gherkin/javascript/test/StreamTest.ts
Users of the Gherkin library may pass a directory to `Gherkin#fromPaths`, assuming it will recurse into directories (it will not). This change causes it to emit an error if a path cannot be read.
=> Gherkin#fromPaths emits an error if a path can't be read

messages/CHANGELOG.md, messages/go/io/ndjson.go, messages/go/messages_test.go
Increase limit of NDJSON messages from 64Kb to 10Mb. Closes #901.
I chose 10Mb because it should be sufficient for most image attachments. If larger attachments are needed (movie attachments probably) we need to rethink the strategy. Maybe make the max size configurable, and/or try to detect if messages are too big.
=> Support up to 10MB NDJSON messages

html-formatter/javascript/Makefile, html-formatter/javascript/webpack.config.js
The `npm-link-shared` hack didn't work because it runs after Make ran npm
install. So at this point `dist/src/main.js` was already created with the
duplicate react include.
By aliasing react inside webpack we can avoid this problem. All versions of
react will be resolved to the direct dependency.
=> html-formatter/javascript: Remove npm-link-shared hack

Dockerfile
To enable to build of `Nokogiri`, we need `libxml2-dev` and `libxslt-dev` on the image.
Previously, we were simply running `apk add libxml2-dev libxslt-dev` during the Ruby build but we do not have the possibility to do so anymore as we run the image as `cukebot` (and `sudo` is not available))
=> Dockerfile: add dependencies for Ruby build

.templates/javascript/default.mk, c21e/javascript/default.mk, compatibility-kit/javascript/default.mk, cucumber-expressions/javascript/default.mk, fake-cucumber/javascript/default.mk, gherkin/javascript/default.mk, html-formatter/CHANGELOG.md, html-formatter/Makefile, html-formatter/javascript/Makefile, html-formatter/javascript/default.mk, html-formatter/javascript/package.json, html-formatter/javascript/src/CucumberHtmlStream.ts, html-formatter/javascript/src/cli-main.ts, html-formatter/javascript/src/index.mustache.html, html-formatter/javascript/test/CucumberHtmlStreamTest.ts, json-formatter/javascript/default.mk, messages/javascript/default.mk, query/javascript/default.mk, react/javascript/default.mk, tag-expressions/javascript/default.mk
Reduce memory footprint for HTML formatter
Stream the HTML as messages are received
Prior to this change we'd buffer all messages in memory and only flush the HTML when the stream is flushed. This consumes too much memory when there are big messages (screenshots)
=> html-formatter: stream messages rather than buffering

cucumber-expressions/CHANGELOG.md, cucumber-expressions/javascript/src/Argument.ts, cucumber-expressions/javascript/src/CombinatorialGeneratedExpressionFactory.ts, cucumber-expressions/javascript/src/CucumberExpression.ts, cucumber-expressions/javascript/src/CucumberExpressionGenerator.ts, cucumber-expressions/javascript/src/Errors.ts, cucumber-expressions/javascript/src/Expression.ts, cucumber-expressions/javascript/src/GeneratedExpression.ts, cucumber-expressions/javascript/src/Group.ts, cucumber-expressions/javascript/src/GroupBuilder.ts, cucumber-expressions/javascript/src/ParameterType.ts, cucumber-expressions/javascript/src/RegexExecArray.ts, cucumber-expressions/javascript/src/RegularExpression.ts, cucumber-expressions/javascript/src/TreeRegexp.ts, fake-cucumber/CHANGELOG.md, fake-cucumber/javascript/src/ErrorMessageGenerator.ts, fake-cucumber/javascript/src/ExpressionStepDefinition.ts, fake-cucumber/javascript/src/IParameterTypeDefinition.ts, fake-cucumber/javascript/src/IStepDefinition.ts, fake-cucumber/javascript/src/PickleTestStep.ts, fake-cucumber/javascript/src/SupportCodeExecutor.ts, fake-cucumber/javascript/src/TestPlan.ts, fake-cucumber/javascript/src/TestStep.ts, fake-cucumber/javascript/src/makePickleTestStep.ts, fake-cucumber/javascript/src/makeTestCase.ts, fake-cucumber/javascript/src/types.ts
Declare functions parameters and return types as ReadonlyArray. This is to avoid accidental mutation of arrays when they shouldn't be.
=> TypeScript: Use ReadOnlyArray

datatable/CHANGELOG.md, datatable/java/datatable/src/main/java/io/cucumber/datatable/CucumberDataTableException.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistryTableConverter.java, datatable/java/datatable/src/main/java/io/cucumber/datatable/UndefinedDataTableTypeException.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTest.java, datatable/java/datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java
As reported in https://github.com/cucumber/cucumber-jvm/issues/1928:
```
Given table1
| aaa | bbb | ccc |
List<String> result1 = table1.asList(String.class);
```
As part of cucumber/cucumber#540 this should have thrown an exception
but no exception was thrown. After fixing this, reviewing the
exceptions revealed that they were rather lacking in clarify. By
including all potential causes rather then a best guess we'll ensure
that all possible fixes have been suggested.
=> datatable/java: Improve error messages

gherkin/javascript/src/index.ts
See https://github.com/cucumber/cucumber-js/pull/1286#discussion_r387779311
`Dialect` is not currently on the main export from gherkin, so in consuming projects we are having to reach into dist directly; this adds it.
=> gherkin/javascript: make Dialect available on main export

Makefile, html-formatter/Makefile, html-formatter/ruby/Makefile
The `html-formatter` depends on the `compatibility-kit`.
Disabled `html-formatter/ruby` because `compatibility-kit/ruby` is
also disabled
=> build: Disable html-formatter/ruby and fix build order

html-formatter/CHANGELOG.md, html-formatter/java/pom.xml, html-formatter/java/src/main/java/io/cucumber/htmlformatter/MessagesToHtmlWriter.java, html-formatter/java/src/test/java/io/cucumber/htmlformatter/MessagesToHtmlWriterTest.java
The html formatter has minimal interactions with the messages library so using a version range here is probably safe and avoids issues with build system configurations that do not allow conflicts between dependencies.
The alternative would be using the `messages` dependency as a `provided` dependency but this results in the main not working without explicitly including a dependency on messages on the classpath.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1963
@aslakhellesoy you can find an explanation of how version ranges work in maven here:
http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
Note that this won't pick up snapshot versions.
=> html-formatter/java Use version range for messages dependency

c21e/javascript/package.json, compatibility-kit/javascript/package.json, cucumber-expressions/javascript/package.json, fake-cucumber/javascript/package.json, gherkin/javascript/package.json, html-formatter/javascript/package.json, json-to-messages/javascript-json/package.json, json-to-messages/javascript/package.json, messages/javascript/package.json, query/javascript/package.json, react/javascript/package.json, tag-expressions/javascript/package.json
The build is [currently failing](https://app.circleci.com/pipelines/github/cucumber/cucumber/2304/workflows/4d6f9882-673f-474f-b16c-1540a86e631b) when trying to run `eslint` in the javascript packages. This is linked to this issue: https://github.com/typescript-eslint/typescript-eslint/issues/2012
In the meantime, this adds the `json-schema` dev dependencies to all the Javascript modules so the build should pass again.
=> Add json-schema everywhere to get the build pass again

tag-expressions/CHANGELOG.md, tag-expressions/java/src/main/java/io/cucumber/tagexpressions/TagExpressionException.java, tag-expressions/java/src/main/java/io/cucumber/tagexpressions/TagExpressionParser.java, tag-expressions/java/src/test/java/io/cucumber/tagexpressions/TagExpressionParserParameterizedTest.java, tag-expressions/java/src/test/java/io/cucumber/tagexpressions/TagExpressionParserSyntaxErrorTest.java, tag-expressions/java/src/test/java/io/cucumber/tagexpressions/TagExpressionParserTest.java
This change makes the original tag expression with the error viable to the user via the exception message.
This change saves the infix string in an object instance variable.  This is then used to create the TagExpressionException object so that the tag expression is visible to the user when an error occurs.
This is required facilitate the fixing of cucumber-jvm bug cucumber/cucumber-jvm#1976.
The tests have been updated to reflect the new exception message.
=> Tag expressions: Tag exception message

cucumber-expressions/CHANGELOG.md, cucumber-expressions/java/pom.xml, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformer.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformerTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/ParameterByTypeTransformerTest.java
This PR aims to support `Optional` types out of the box in Expressions.
Add support for `Optional<T>` in the (default) `BuiltInParameterTransformer`.
The main goal is to be able to describe a step definition with optional capture groups. For instance: `"^I am logged in(?: as (.+))?$"`.
`Optional` as method parameters are generally considered a bad practice in Java and you would usually expect a `String` parameter with a `null` value in this case.
But on the other hand, other JVM languages (like Scala) consider `null` as forbidden and would benefit from mapping this as an `Optional<String>`.
(Related to https://github.com/cucumber/cucumber-jvm-scala/issues/3)
Tests added in `BuiltInParameterTransformerTest` and `ParameterByTypeTransformerTest` (with Jackson JDK8 Module).
I'm just starting …
=> cucumber-expressions: Support for Optional

gherkin/CHANGELOG.md, gherkin/ruby/gherkin-ruby.razor, gherkin/ruby/lib/gherkin.rb, gherkin/ruby/lib/gherkin/ast_builder.rb, gherkin/ruby/lib/gherkin/parser.rb, gherkin/ruby/lib/gherkin/stream/parser_message_stream.rb, gherkin/ruby/lib/gherkin/token_matcher.rb, gherkin/ruby/lib/gherkin/token_scanner.rb, json-formatter/ruby/Gemfile
This PR changes internal requires inside the `gherkin-ruby` gem to use `require_relative`. 
`require_relative` is faster because it doesn't search the `$LOAD_PATH`, it's more clear, because it makes it more explicit where the code is being loaded from, and it can avoid actually requiring the wrong code.
Normally this doesn't make a difference, but in this case, since the same files are also present in the old defunct `gherkin` gem (if I have understood the migration alright), it can prevent errors.
In my case, I was upgrading `cucumber`, but some dependencies still were pinned to the old `gherkin` gem. This was causing some requires to actually load code from the old project, causing weird errors like:
```
1 processes for 1 features, ~ 1 features per process
wrong number of arguments …
```
=> gherkin: Prefer `require_relative` for internal requires

compatibility-kit/ruby/features/attachments/attachments_steps.rb
I had to do an awful monkey patch to handle attaching byte strings in CCK with cucumber-ruby 3.x, but this was solved by 3.2.0.
=> Remove monkey patch which is not needed after 3.2 release

html-formatter/CHANGELOG.md, html-formatter/java/src/main/java/io/cucumber/htmlformatter/MessagesToHtmlWriter.java
Fixes: https://github.com/cucumber/cucumber/issues/1045
=> html-formatter/java: Always use UFT_8 encoding

html-formatter/ruby/cucumber-html-formatter.gemspec
Updated gemspec metadata for the `html-formatter` sub-project.
As per [metadata specification](https://guides.rubygems.org/specification-reference/#metadata), add missing metadata to the gemspec file and update its changelog URI.
This'll allow people to more easily access docs and source code, raise issues and read the changelog.
These links will appear on the [cucumber-html-formatter Rubygems page](https://rubygems.org/gems/cucumber-html-formatter) at and will also be available via the Rubygems API after the next release.
My team uses an automated bundle update process that annotates pull-requests and it makes it easier for reviewers when there is a changelog link.
I believe tests don't apply here.
Since there is no code change, I believe none of these apply.
=> html-formatter: Ruby gem metadata

gherkin/c/include/rule_type.h
Problem: rule_type.h required to compile library
Solution: Add the generated rule_type.h
Having the generated files part of the source control omits new users
from installing all the dependencies required to generate the file.
=> [gherkin-c] Problem: rule_type.h required to compile library

cucumber-expressions/CHANGELOG.md, cucumber-expressions/examples.txt, cucumber-expressions/go/cucumber_expression_test.go, cucumber-expressions/go/examples.txt, cucumber-expressions/java/examples.txt, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/Group.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/GroupBuilder.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterType.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeRegistry.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionTest.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/RegularExpressionTest.java, cucumber-expressions/javascript/examples.txt, cucumber-expressions/javascript/src/Group.ts, cucumber-expressions/javascript/src/GroupBuilder.ts, cucumber-expressions/javascript/src/ParameterTypeRegistry.ts, cucumber-expressions/javascript/test/CucumberExpressionTest.ts, cucumber-expressions/javascript/test/TreeRegexpTest.ts, cucumber-expressions/ruby/examples.txt, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/group.rb, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_registry.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
When using a regular expression with multiple optional capturing groups. Absent
groups (i.e. a null value) were filtered out. This makes optional
capture groups hard to use:
For example given a parameter type with optional capturing groups:
```java
parameterTypeRegistry.defineParameterType(new ParameterType<>(
"textAndOrNumber",
singletonList("([A-Z]+)?(?: )?([0-9]+)?"),
new TypeReference<List<String>>() {
}.getType(),
new CaptureGroupTransformer<List<String>>() {
@Override
public List<String> transform(String... args) {
return ...;
}
},
false,
false)
);
```
Now the intuition would be that `args[0]` always contains letters and `args[1]`
always contains numbers.
So when we match the expression `{textAndOrNumber}` against `TLA 123`. Then
`args = ["TLA", "123"]`. However when matched `TLA` …
=> cucumber-expressions: Retain position of optional groups

gherkin/CHANGELOG.md, gherkin/javascript/src/pickles/compile.ts, gherkin/javascript/test/ParserTest.ts
=> gherkin/javascript: Escape regex characters in table header

gherkin/CHANGELOG.md, gherkin/ruby/lib/gherkin/query.rb, gherkin/ruby/spec/gherkin/query_spec.rb
This is a fix for [cucumber-ruby#1427](https://github.com/cucumber/cucumber-ruby/issues/1427)
It can occur when there is an empty `.feature` file in the features directory. Surprisingly (or not), the error is only raised when trying to filter the scenarios by tags.
=> gherkin-query ruby: do not try to lookup feature attributes if nil

cucumber-expressions/CHANGELOG.md, cucumber-expressions/examples.txt, cucumber-expressions/go/cucumber_expression_generator_test.go, cucumber-expressions/go/examples.txt, cucumber-expressions/go/parameter_type_matcher.go, cucumber-expressions/java/examples.txt, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ParameterTypeMatcher.java, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/CucumberExpressionGeneratorTest.java, cucumber-expressions/javascript/examples.txt, cucumber-expressions/javascript/src/ParameterTypeMatcher.ts, cucumber-expressions/ruby/examples.txt, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type_matcher.rb
Numerical parameters should be bounded by whitespace, punctuation or symbols
on both sides.
```
$1.50 -> ${double}
15° Celsius -> {int}° Celcius
i18n -> i18n
$15m -> $15m
```
Fixes: https://github.com/cucumber/cucumber/issues/844
=> cucumber-expressions: Use Unicode symbols as a parameter boundary in snippets

gherkin/go/README.md
=> /gherkin/go: fix Gherkin link

messages/javascript/test/verifyStreamContract.ts
Add name for function verifyStreamContract (the linter was failing as it could not find a name apparently)
Example of failed build: https://app.circleci.com/pipelines/github/cucumber/cucumber/3062/workflows/d42c1f7b-0606-4e32-94d2-46fc6877fe8c/jobs/97765
That does not really explains why it works in the parallel build that said.
=> Fix linking error during serial build

create-meta/java/pom.xml, create-meta/java/src/main/java/io/cucumber/createmeta/CreateMeta.java, create-meta/java/src/test/java/io/cucumber/createmeta/CreateMetaTest.java, messages/CHANGELOG.md, messages/java/pom.xml, messages/java/src/main/java/io/cucumber/messages/NdjsonToMessageIterable.java, messages/java/src/main/java/io/cucumber/messages/ProtocolVersion.java, messages/java/src/main/resources/io/cucumber/messages/version.properties, messages/java/src/test/java/io/cucumber/messages/MessageSerializationContract.java, messages/java/src/test/java/io/cucumber/messages/NdjsonSerializationTest.java, messages/java/src/test/java/io/cucumber/messages/ProtobufSerializationTest.java, messages/java/src/test/java/io/cucumber/messages/ProtocolVersionTest.java, messages/java/src/test/java/io/cucumber/messages/TimeConversionTest.java
Because `Messages.class.getPackage().getImplementationVersion()` can not reliably determine the implementation version of the messages jar (e.g. when the jar is shaded). we should determine the message protocol version in a different way. By adding a resource bundle with the version of messages included we can avoid this problem. 
Fixes: https://github.com/cucumber/cucumber/issues/1127
=> messages: Use resource bundle to determine message protocol version

react/CHANGELOG.md, react/javascript/src/filter/filterByStatus.ts, react/javascript/src/index.ts
Expose `filterByStatus` to enable custom filtering of displayed `GherkinDocuments`.
Also update the signature so it's clear it can also return `null`.
=> Expose filterByStatus and fix signature

gherkin/CHANGELOG.md, gherkin/c/gherkin-languages.json, gherkin/dotnet/Gherkin/gherkin-languages.json, gherkin/gherkin-languages.json, gherkin/go/dialects_builtin.go, gherkin/go/gherkin-languages.json, gherkin/go/go.mod, gherkin/go/go.sum, gherkin/java/src/main/resources/io/cucumber/gherkin/gherkin-languages.json, gherkin/javascript/src/gherkin-languages.json, gherkin/objective-c/GherkinLanguages/gherkin-languages.json, gherkin/perl/gherkin-languages.json, gherkin/python/gherkin/gherkin-languages.json, gherkin/ruby/lib/gherkin/gherkin-languages.json
Remove letter case variations of Gherkin keywords since their presence causes different annotation classes to be generated during the build of Cucumber-JVM (depending on what OS it was built on).
I discovered this when I was checking semantic versioning of Cucumber-JVM, building on MacOS.
```
CHECK_SEMANTIC_VERSION=true mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true
...
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.12.1:check (check) on project cucumber-java: The following API problems caused the build to fail:
[ERROR] java.class.removed: @interface io.cucumber.java.ht.SipozeKe: Class was removed. (breaks semantic versioning)
```
This is related to https://github.com/cucumber/cucumber-jvm/pull/2085
=> Remove letter case variations from Gherkin

html-formatter/CHANGELOG.md, html-formatter/javascript/package.json, html-formatter/javascript/src/cli-main.ts
Fixes the `@cucumber/html-formatter` CLI when the package is installed as a project dependency (rather than only working when installed globally).
Installing to a project like `npm i @cucumber/html-formatter` and then running in an npm script would currently yield an error like:
```
[Error: ENOENT: no such file or directory, open '/Users/davidgoss/Documents/Projects/html-formatter-test/node_modules/@cucumber/html-formatter/dist/src/../../node_modules/@cucumber/react/dist/src/styles/cucumber-react.css'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/Users/davidgoss/Documents/Projects/html-formatter-test/node_modules/@cucumber/html-formatter/dist/src/../../node_modules/@cucumber/react/dist/src/styles/cucumber-react.css'
}
npm ERR! Test failed.  See above for more details.
```
This is …
=> html-formatter: fix when installed locally to node project

messages/CHANGELOG.md, messages/go/io/ndjson.go, messages/go/messages_test.go, messages/java/src/main/java/io/cucumber/messages/NdjsonToMessageIterable.java, messages/java/src/test/java/io/cucumber/messages/NdjsonSerializationTest.java, messages/javascript/src/NdjsonToMessageStream.ts, messages/javascript/test/NdjsonStreamTest.ts, messages/ruby/lib/cucumber/messages/ndjson_to_message_enumerator.rb, messages/ruby/spec/cucumber/messages/ndjson_serialization_spec.rb
Sometimes an NDJSON stream can contain a newline at the end. This would cause the NDJSON readers to throw an error. With this change, empty lines are ignored (even if they are not at the end).
=> Ignore empty lines when reading NDJSON

gherkin/c/CMakeLists.txt
run tests post build so build will fail if tests fail.
Tests are implemented as a post build step.  Determining what failed is hard when used in this manner.  Tests should be added as ctest tests, which is the norm for cmake.
Moved tests into add_test
run all tests as a post build step.  **Build will still fail if tests fail**
Output on build if there is a failing tests is now
```
37/37 Test #37: /testdata/good/very_long.feature ......................................   Passed    4.30 sec
92% tests passed, 3 tests failed out of 37
Total Test time (real) =   5.96 sec
The following tests FAILED:
11 - /testdata/good/i18n_emoji.feature (Failed)
12 - /testdata/good/i18n_fr.feature (Failed)
13 - /testdata/good/i18n_no.feature (Failed)
Errors while running CTest
```
Some tests fail on windows. …
=> gherkin/c: change tests from post build step to tests.

gherkin/c/.gitignore, gherkin/c/CMakeLists.txt
check for m.lib link to if exists.  Assume not needed if doesn't exist.
Add out/ and build/ to .gitignore
Issue 1198
tested build with:
- MSVC
- MSVC-Clang
- GCC Ubuntu 20.04
- Clang Ubuntu 20.04
- OSX Clang AppleClang 12.0.0.12000032
Changed CMakeLists.txt
- [? ] I have updated the CHANGELOG accordingly.
-- Can do, need guidance if this applies.
=> gherkin-c Fixes 1198 can't build with msvc

gherkin/c/CMakeLists.txt
Remove dubious custom target in build system is ninja.
Ninja is a cmake build system.  It can't be used on this project due to the syntax of the custom target.  I believe that this custom target is a defect, and can't be used at all, but just in case, I'm only excluding it for the ninja build system.
ninja is what is used by vcpkg, so although this library is included, it fails to build, because of this custom target.
fixes issue #1200 
built using the following scenarios:
- readme.md instructions
- windows
- ubuntu 20.04
- msvc ninja
- msvc
- msvc-clang
- ubuntu 20.04 clang
- ubuntu 20.04 gcc
for readme instructions:
mkdir build
cd build
cmake ..
cmake --install .
for msvc build:
open folder with msvc
generate build configuration using defaults for:
- x64-Debug
- x64-Clang-Debug
- …
=> gherkin/c: Fixes Issue #1200 build fails when using ninja generator.

.templates/go/default.mk, cucumber-expressions/go/default.mk, demo-formatter/go/default.mk, gherkin/go/default.mk, json-formatter/go/default.mk, messages/go/default.mk, tag-expressions/go/default.mk
This fixes the make dependency rules such that running `make` twice in a `go` directory does not build the executables on the 2nd run. This significantly shortens the build time for incremental builds.
This regression of make dependencies was introduced in #1171
=> Fix dependencies in go makefiles

create-meta/java/src/main/java/io/cucumber/createmeta/CreateMeta.java, create-meta/java/src/test/java/io/cucumber/createmeta/CreateMetaTest.java, create-meta/testdata/CodeShip.txt, create-meta/testdata/CodeShip.txt.json, create-meta/testdata/GoCD.txt, create-meta/testdata/GoCD.txt.json
This fixes #1228 by handling null explicitly.
I'm unsure, if it would be worth to add acceptance tests for all available CIs.
=> create-meta/java: handle null values in ci dict

messages/CHANGELOG.md, messages/go/io/ndjson.go, messages/go/messages.pb.go, messages/go/messages_test.go, messages/java/src/main/java/io/cucumber/messages/NdjsonToMessageIterable.java, messages/java/src/test/java/io/cucumber/messages/NdjsonSerializationTest.java, messages/javascript/src/NdjsonToMessageStream.ts, messages/javascript/test/NdjsonStreamTest.ts, messages/ruby/lib/cucumber/messages/ndjson_to_message_enumerator.rb, messages/ruby/spec/cucumber/messages/ndjson_serialization_spec.rb
When the NDJSON stream contains lines that are not valid JSON, we want the error to include the line to make it easier to diagnose the problem.
=> include offending line in error message

gherkin/perl/.gitignore, gherkin/perl/Makefile
`cpanm` defaults to writing its packages to global locations. To work around that, the environment needs to be set correctly, which is exactly what Carton is helping us do.
Together with the issued change for the Docker development image (installing Carton), this change sets up the foundation needed to build the next PR I'm about to issue: an update for the Perl implementation of Gherkin.
This PR has been tested on the cucumber-build Docker image and succeeds testing when run on top of the updated Perl implementation.
=> gherkin-perl: Use Carton (Perl's Bundler) to store project-local dependencies

cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/Group.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/GroupBuilder.java, cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java
Make the RegExp Group parsing of Cucumber accessible in a way  that it could be used for descending processing steps.
I'm currently overhaul the [cucumber-eclipse plugin](https://github.com/cucumber/cucumber-eclipse) to provide better editing capabilities and user experience.
There are these main goals:
1. reuse as much code as possible from cucumber-jvm to prevent diverging results between IDE and the actual cucumber run and reduce code-duplication/implementation of features already available (especially parsers)
2. provide a better user-experience, e.g user should be able to tab-trhough parameters and simply type instead of placing cursor manually
With this change it is possible to use the same regex group parsing that cucumber-jvm uses.
I use a modified version of cucumber in …
=> cucumber-expressions/java: Expose regex group parser api

gherkin/perl/Makefile
Make the release process work for Gherkin's Perl implementation
The Makefile is missing the `pre-release` target.
Couldn't commit directly to `master` due to it being a restricted branch at the time (@aslakhellesoy says due to a running CircleCI build).
=> [gherkin-perl]: Add release machinery

Makefile, gherkin/perl/.gitignore, gherkin/perl/MANIFEST.SKIP, gherkin/perl/Makefile, gherkin/perl/cpanfile, gherkin/perl/dist.ini
Fix a number of issues in the Gherkin Perl release process
1. [Test failures in CPANTESTERS](http://matrix.cpantesters.org/?dist=Gherkin+17.0.1) due to incorrect declaration of minimum Perl version
2. Release archive contains several undesirable artifacts (perl5/ subdirectory, test directories)
3. Changelog not updated on 17.0.1 release (because 17.0.0 was released from the same repo)
4. Release CHANGELOG.md as itself instead of as CHANGES (which is rendered as plain text)
5. Make release process truely non-interactive
Note that all the removed lines in brackets are now hidden behind the `[@Filter]\n-bundle=@Basic` bit. 
This has been tested locally by regenerating the release archive for 17.0.1, which is 8MB on CPAN, but only 31kB locally, after these changes.
Bugfixes for the release …
=> [gherkin-perl] Fine-tune release engineering

messages/java/pom.xml
Renovate keeps creating 2 different MR's for each dependency. This is annoying and consuming time on CI.
By using a single version property, Renovate will only create 1 MR.
=> messages/java: Use single property for protobuf version

ARCHITECTURE.md
I've been onboarding @aurelien-reeves and finally decided to describe in more detail how the various pieces fit together. 
I recently read [this blog post](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) which recommends a separate `ARCHITECTURE.md` file.
Should we create this file (as proposed here) and move some of the architecture-related architecture content from other files?
Or do we want to keep all of it in the `README.md`.
=> Start an architecture doc

.templates/javascript/default.mk, compatibility-kit/javascript/default.mk, compatibility-kit/javascript/package.json, create-meta/javascript/default.mk, create-meta/javascript/package.json, cucumber-expressions/javascript/default.mk, cucumber-expressions/javascript/package.json, fake-cucumber/javascript/default.mk, fake-cucumber/javascript/package.json, gherkin-streams/javascript/default.mk, gherkin-streams/javascript/package.json, gherkin-utils/javascript/default.mk, gherkin-utils/javascript/package.json, gherkin/javascript/default.mk, gherkin/javascript/package.json, html-formatter/javascript/default.mk, html-formatter/javascript/package.json, json-formatter/javascript-testdata/default.mk, json-to-messages/javascript-testdata/default.mk, json-to-messages/javascript/default.mk, json-to-messages/javascript/package.json, message-streams/javascript/default.mk, message-streams/javascript/package.json, messages/javascript/default.mk, messages/javascript/package.json, query/javascript/default.mk, query/javascript/package.json, react/javascript/default.mk, tag-expressions/javascript/default.mk, tag-expressions/javascript/package.json
The build of javascript modules has to be done from the root folder of
the mono-repo. So `default.mk` has been updated to do that.
`package.json` have also been updated. `prepublishOnly` has been kept
and fixed as kinda last validation before publish.
`html-formatter` `prepublishOnly` script does not execute webpack
anymore as this is now done using `make` thanks to the Makefile.
=> Fix the release process for javascript modules

compatibility-kit/javascript/package.json
Not sure if this was intentional - looks to have been added as part of the big workspaces PR.
`@cucumber/compatibility-kit@4.0.0` is not on npm and I suspect this may be why - `npm publish` would have aborted with this in.
=> cck: make javascript package publishable

cucumber-expressions/javascript/package.json, query/CHANGELOG.md, query/javascript/package.json
Before:
After:
Seems likely that npm7 has different handling of `files` (specifically of `"*"` in relation to what's gitignored), though I can't find documentation to prove that.
The lone `index.js` making its way in was perhaps because of the reference to it in the `main` field.
=> build: fix files spec in package.json for query, cucumber-expressions

cucumber-expressions/CHANGELOG.md, cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/errors.rb, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/cucumber_expression_spec.rb
This accessor on `UndefinedParameterTypeError` already exists on the Java and TypeScript implementations.
Adding this will let us access the name of the undefined parameter type more cleanly in https://github.com/cucumber/cucumber-ruby/blob/4c09cb7f2e5d3fa8f34721ef917749c786fc0976/lib/cucumber/glue/registry_and_more.rb#L93-L94
=> Add UndefinedParameterTypeError#undefined_parameter_type_name

messages/CHANGELOG.md, messages/ruby/lib/cucumber/.gitignore, messages/ruby/lib/cucumber/messages.pb.rb
This adds the generated `messages.pb.rb` to git. The motivation for this is to be able to depend on unreleased versions of the gem from `cucumber-ruby`.
It should fix [this CI build error](https://app.circleci.com/pipelines/github/cucumber/cucumber-ruby/1061/workflows/8e9f2db3-78c0-46c5-b85a-b05613b65a15/jobs/10126). 
The generated code is tidy, so I don't expect this will cause significant merge conflicts.
=> Add generated messages.pb.rb to git

gherkin/CHANGELOG.md, gherkin/perl/lib/Gherkin/Pickles/Compiler.pm
Close #1494: Reinstate Perl 5.10.1 compatibility
The 'yada-yada' operator (triple-dot) was added to Perl 5.12. It's functionally equivalent to `die "Unimplemented";`. The rest of the code base is 5.10.1 compliant. These two (minor) issues do not seem like a good reason to increase the requirement.
`make test` in the docker development environment.
=> gherkin-perl: Reinstate Perl 5.10.1 compatibility

gherkin-streams/CHANGELOG.md, gherkin-streams/javascript/README.md, gherkin-streams/javascript/src/GherkinStreams.ts, gherkin-streams/javascript/src/SourceMessageStream.ts, gherkin-streams/javascript/src/index.ts, gherkin-streams/javascript/test/StreamTest.ts, gherkin/javascript/README.md
If `relativeTo` is provided in the options object for `fromPaths`, we'll calculate the `uri` for the `source` message (which is reused in subsequent ones) relative to that.
This is useful where e.g. we have a set of absolute paths for features which were found based on user input, but we don't want to show the full absolute path in reports etc - instead we want to show them relative to the root of the project we're running from (or something else in other edge cases where people use Gherkin directly).
See https://github.com/cucumber/cucumber-js/issues/1534#issuecomment-754716365
=> gherkin-streams: accept an optional `relativeTo` path for uris

.circleci/config.yml, .templates/javascript/default.mk, Makefile, compatibility-kit/javascript/default.mk, create-meta/javascript/default.mk, cucumber-expressions/javascript/default.mk, fake-cucumber/javascript/default.mk, gherkin-streams/javascript/default.mk, gherkin-utils/javascript/default.mk, gherkin/javascript/default.mk, html-formatter/javascript/default.mk, json-formatter/javascript-testdata/default.mk, json-to-messages/javascript-testdata/default.mk, json-to-messages/javascript/default.mk, message-streams/javascript/default.mk, messages/javascript/default.mk, query/javascript/default.mk, react/javascript/default.mk, tag-expressions/javascript/default.mk
This avoids running npm install when we specify e.g. `LANGUAGES=java make`
=> Only run npm install for javascript modules

gherkin/CHANGELOG.md, gherkin/Makefile, gherkin/perl/lib/Gherkin/AstBuilder.pm, gherkin/perl/lib/Gherkin/Pickles/Compiler.pm
The JSON schema specifies required output for some fields which used to be absent in the output under protobuf messages.
Bring back compatibility and testability.
See JSON schema commits and discussion context.
All regular tests are now passing again.
Compatibility with the spec.
=> [gherkin-perl] Update to conform to JSON schema output specification

.circleci/config.yml
Based on the example from Gherkin/dotNet, add Perl tests to the
parallel build.
=> [build] Add Gherkin/Perl to the parallel build

create-meta/CHANGELOG.md, create-meta/README.md, create-meta/ciDict.json, create-meta/java/src/main/java/io/cucumber/createmeta/CreateMeta.java, create-meta/java/src/main/java/io/cucumber/createmeta/VariableExpression.java, create-meta/java/src/main/resources/io/cucumber/createmeta/ciDict.json, create-meta/java/src/test/java/io/cucumber/createmeta/CreateMetaTest.java, create-meta/java/src/test/java/io/cucumber/createmeta/VariableExpressionTest.java, create-meta/javascript/package.json, create-meta/javascript/src/ciDict.json, create-meta/javascript/src/createMeta.ts, create-meta/javascript/src/evaluateVariableExpression.ts, create-meta/javascript/test/evaluateVariableExpressionTest.ts, create-meta/ruby/lib/cucumber/ciDict.json, create-meta/ruby/lib/cucumber/create_meta.rb, create-meta/ruby/lib/cucumber/create_meta/variable_expression.rb, create-meta/ruby/spec/cucumber/create_meta_spec.rb, create-meta/ruby/spec/cucumber/evaluate_variable_expression_spec.rb, create-meta/testdata/Bitrise.txt, create-meta/testdata/Bitrise.txt.json, create-meta/testdata/CodeShip.txt, create-meta/testdata/GoCD.txt, create-meta/testdata/GoCD.txt.json, create-meta/testdata/Jenkins.txt, create-meta/testdata/Jenkins.txt.json
This fixes several bugs in create-meta where we weren't properly generating the right values.
This PR also introduces a new expression language - `${variable/pattern/replacement}` - similar to [bash parameter substitution](https://tldp.org/LDP/abs/html/parameter-substitution.html), but inspired from [sed's s command](https://www.gnu.org/software/sed/manual/html_node/The-_0022s_0022-Command.html) which provides support for capture group back-references in the replacement.
This will make it easier to add support for other CI servers in the future, without any code changes.
=> Create meta improvements

gherkin/CHANGELOG.md, gherkin/ruby/lib/gherkin/query.rb, gherkin/ruby/spec/gherkin/query_spec.rb
Fix tagging of Rules
During the Gherkin Query cache step where it finds all data and relates them to specific AST Node IDs, it wasn't storing tag data. This was likely because similar to features, it needs to look "up" and not down through descendents
Fix Ruby
CI
Altered tests in cucumber-ruby
Discussion during general meeting about executing portions of the regular CCK against all flavours of cucumber
=> gherkin/ruby: Fix tagging of rules

messages/CHANGELOG.md, messages/jsonschema/scripts/codegen.rb, messages/jsonschema/scripts/templates/ruby.rb.erb, messages/ruby/lib/cucumber/messages.dtos.rb
The point of the ruby DTOs was to stick with ruby standard.
We missed to convert cameCase attribute names to snake_case in the previous PR: #1574
=> Messages: ruby: Convert DTOs attributes from camelCase to snake_case

.templates/go/default.mk, cucumber-expressions/go/default.mk, demo-formatter/go/default.mk, gherkin/go/default.mk, json-formatter/go/default.mk, messages/go/default.mk, tag-expressions/go/default.mk
Change default Makefile for Go packages to rebuild if the `go.mod` file changes
I'm working on #1550 and fiddling about with the `go.mod` files. It seems the Makefile needs this dependency expressed.
=> Rebuild go packages if go.mod changes

react/CHANGELOG.md, react/javascript/src/components/gherkin/Anchor.module.scss, react/javascript/src/components/gherkin/StepItem.module.scss
Stop the anchor link for the step from overlapping the status icon.
(Must have missed this in the big styling PR last month.)
Before:
After:
=> react: alter left offset for anchor in step line

.circleci/config.yml
To get changes from https://github.com/cucumber/build/pull/34
Should unblock https://github.com/cucumber/common/pull/1610
=> build: use latest cucumber/build image

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/go.mod, demo-formatter/go/cmd/main.go, demo-formatter/go/go.mod, gherkin/CHANGELOG.md, gherkin/go/cmd/main.go, gherkin/go/gherkin-generate-tokens/gherkin-generate-tokens.go, gherkin/go/go.mod, json-formatter/CHANGELOG.md, json-formatter/go/cmd/main.go, json-formatter/go/go.mod, messages/CHANGELOG.md, messages/go/go.mod, tag-expressions/CHANGELOG.md, tag-expressions/go/go.mod
Ref #1550
This PR changes each of the go module's paths to point to inside the monorepo instead of to the mirror subrepo.
This is to prepare the ground for #1608 to update the references that point _to_ these modules, once this PR has been merged to main, since Go default to look for the `go.mod` files on the repo's default branch.
=> Point go module paths to monorepo

cucumber-expressions/CHANGELOG.md, cucumber-expressions/javascript/package.json, cucumber-expressions/javascript/src/Group.ts, cucumber-expressions/javascript/src/GroupBuilder.ts, cucumber-expressions/javascript/src/RegexExecArray.ts, cucumber-expressions/javascript/src/TreeRegexp.ts, cucumber-expressions/javascript/test/TreeRegexpTest.ts, package-lock.json
Use [RegExpExecArray#indices](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) to get the position of capture groups.
This PR removes the dependency on the [becke-ch--regex--s0-0-v1--base--pl--lib](https://www.npmjs.com/package/becke-ch--regex--s0-0-v1--base--pl--lib) library and uses `RegExpExecArray#indices` instead.
[RegExp Match Indices](https://github.com/tc39/proposal-regexp-match-indices) were introduced in v8 v9.0.259. The first Node.js release to use a v8 newer than that is [16.4.0](https://nodejs.org/en/download/releases/).
Since we cannot drop support for Node.js < 16.4.0 until 2023/2024, the implementation currently uses a [polyfill](https://github.com/rbuckton/regexp-match-indices).
The main motivation for this change is to stop …
=> Use native RegExp Match indices

suggest/CHANGELOG.md, suggest/javascript/README.md, suggest/javascript/features/step_definitions/steps.ts, suggest/javascript/features/support/World.ts, suggest/javascript/src/StepDocumentBuilder.ts, suggest/javascript/src/lspCompletionSnippet.ts, suggest/javascript/src/types.ts, suggest/javascript/test/Index.test.ts, suggest/javascript/test/StepDocumentBuilder.test.ts, suggest/javascript/test/bruteForceIndex.ts, suggest/javascript/test/fuseIndex.ts, suggest/javascript/test/jsSearchIndex.ts, suggest/javascript/test/lspSnippet.test.ts
Change the `StepDocument` so it is an object with a `suggestion` string and a `segments` array.
We don't want to display the actual LSP snippet in the suggestions the user sees. The LSP snippet should never be
seen by users - it's only passed to the editor to build the inserted text.
By adding a `suggestion` string, we can display something nicer to the user, such as `I have {int} cukes in my {word}`.
=> Change StepDocument to have suggestion and segments

gherkin/perl/dist.ini
Copy the 'release-includes-unversioned artifacts' risk mitigation
to gherkin-perl to get consistent packaging.
=> [gherkin-perl] Align dist.ini with messages-perl

Makefile
This means we have a single source of truth for the build image version.
It's been duplicated in the CircleCI config and the Makefile, and the Makefile had drifted out of date. Now we're reading the value to use in the Makefile from the CircleCI config, so we only have to change it in on place.
I ran `make docker-run`
=> Read Makefile build image version from CI config

.templates/perl/default.mk, gherkin/perl/Makefile, gherkin/perl/default.mk, messages/perl/default.mk
Make sure no stale dependencies are hanging around when creating a release.
Current process isn't stable enough as per #1723.
Closes #1723.
=> [gherkin-perl] Release engineering stability improvements

language-server/javascript/src/CucumberInfoStream.ts, language-server/javascript/src/makeCucumberInfo.ts, language-server/javascript/test/CucumberInfoStream.test.ts, language-service/CHANGELOG.md, language-service/javascript/src/CucumberInfo.ts, language-service/javascript/src/index.ts
A `CucumberInfo` object is needed to power the Monaco editor. In a browser we don't have a (Node.js) message stream, but an array of messages loaded over HTTP. This PR extracts the logic from the `CucumberInfoStream` to a separate class.
=> Add CucumberInfo/CucumberInfoBuilder

gherkin/CHANGELOG.md, gherkin/perl/Makefile, gherkin/perl/cpanfile, gherkin/perl/lib/App/gherkin.pm, gherkin/perl/lib/Gherkin.pm, gherkin/perl/lib/Gherkin/AstBuilder.pm, gherkin/perl/lib/Gherkin/Pickles/Compiler.pm
Change the Gherkin implementation to use real Cucumber::Messages instead of hashes that look like them.
Since Gherkin existed since way before Cucumber::Messages, its prior implementations didn't build upon them. With the recent implementation and release of Cucumber::Messages for Perl, now is the time to move the implementation over from the surrogates to the real thing.
With this change, the Perl implementation of Gherkin moves closer to its equivalents in other languages.
The conformance tests.
=> [gherkin-perl] Implement Gherkin on top of Cucumber::Messages

language-service/CHANGELOG.md, language-service/javascript/src/getGherkinCompletionItems.ts, language-service/javascript/test/getGherkinCompletionItems.test.ts, monaco/CHANGELOG.md, monaco/javascript/example/index.js, monaco/javascript/src/index.ts
Two fixes:
* `@cucumber/language-service`: Fix completion items so they always replace the current line rather than appending at the end.
* `@cucumber/monaco`: Register diagnostic event on an editor instance so diagnostics are properly updated.
=> Monaco lsp fixes

react/CHANGELOG.md, react/javascript/src/components/app/GherkinDocumentList.tsx, react/javascript/src/components/customise/CustomRendering.tsx, react/javascript/src/components/gherkin/GherkinDocument.tsx
Make the `<GherkinDocument>` component customiseable
I want to override it so I can display an editor based on `@cucumber/monaco`
=> React customise gherkin document

tag-expressions/python/.bumpversion.cfg, tag-expressions/python/README.rst, tag-expressions/python/cucumber_tag_expressions/__init__.py, tag-expressions/python/pytest.ini, tag-expressions/python/setup.py, tag-expressions/python/tox.ini
Perform some cleanups and updates before a new release of this package can be published on https://pypi.org .
* FIXED: Out-of-date version info in some places
* UPDATED: `tox.ini` to use newer Python versions
* README: Use badge for CircleCI build server status (used in published version on pypi.org; was still using Travis CI)
PATCH RELEASE CONTAINS:
* FIX #1736 (with pull #1742 ; required by: `setuptools >= 58.0.2`)
Prepare for next release of `tag-expressions-python`.
Normal test suite was run with tox.
BUT: Only cosmetic changes were performed here.
=> tag-expressions-python: Prepare release v4.0.1

create-meta/java/pom.xml, cucumber-expressions/java/pom.xml, html-formatter/java/pom.xml, messages/java/pom.xml, tag-expressions/java/pom.xml
Unlike JUnit4, JUnit5 is a multi-module test framework. The version of these
modules should be kept in sync. This is best managed by using the JUnit Bill
of Materials.
When used in the dependency management section this allows individual JUnit
modules to be used without a version. They'll implicitly have the version
specified in the BOM.
By having a single version this should also ensure that tools like Renovate
will update all versions consistently.
=> java: Use JUnit BOM to manage JUnit5 dependencies

cucumber-expressions/CHANGELOG.md, cucumber-expressions/go/regular_expression_test.go, cucumber-expressions/java/src/test/java/io/cucumber/cucumberexpressions/RegularExpressionTest.java, cucumber-expressions/javascript/src/GroupBuilder.ts, cucumber-expressions/javascript/test/RegularExpressionTest.ts, cucumber-expressions/javascript/test/TreeRegexpTest.ts, cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/regular_expression_spec.rb
This is a fix for #1329.
The bug was only present in the JavaScript implementation, but tests have been added to all implementations.
=>  Correctly match empty string. Fixes #1329.

messages/java/pom.xml
Jackson added more module infos to their project. These should not be included
in the shaded jar as this properly messes up encapsulation.
=> messages/java: Exclude module info from shaded jar

gherkin/python/.gitignore, gherkin/python/Makefile, gherkin/python/requirements.txt, gherkin/python/tox.ini
FIX CI build problems for PR #1779 (step 1):
* Use "pytest" instead of "nose" as test runner
HINT: "nose" causes problems in Python 3.10 (CI build failures)
HINT: Additional changes for step 2 are described in PR #1779 (analysis).
* Add "tox.ini" to simplify tests w/ different Python versions in the future.
* Makefile: Replace "nose" with "pytest" as test runner for unit tests.
* Makefile: Added explicit "test" target to run unit tests (instead of implicit).
Using `tox` to run unit tests in different Python version environments:
```
$ pip install tox
$ tox -e py27
$ tox -e py39
$ tox -e py310
```
=> gherkin-python: FIX CI build problems for PR #1779

gherkin/python/.coveragerc, gherkin/python/.gitignore, gherkin/python/CONTRIBUTING.md, gherkin/python/pytest.ini, gherkin/python/requirements.txt, gherkin/python/test/count_symbols_test.py, gherkin/python/test/gherkin_test.py, gherkin/python/test/pickles_test/compiler_test.py, gherkin/python/tox.ini
Replace "nose" with "pytest" as test framework (step 2) fro unit tests.
"nose" is no longer maintained.
DEPENDS ON:
* PR #1819: Use "pytest" as test runner instead of "nose" (aka: step 1)
RELATED TO:
* PR #1779: "nose" caused problem in CI builds since Python 3.10.
* Replace nose.tools (assert helpers) with pytest equivalent in tests.
* Remove "nose" usage (in: test/*.py, "requirements.txt")
In addition:
* Simplify test coverage by using "tox.ini"
* PREPARED: Use of HTML test reports (with: pytest-html)
Using `nose` cause problems in the CI build with Python 3.10.
This PR provides the second step that finally allows to remove `nose` completely.
`pytest` is used instead (as test runner, assert-helper where needed).
* Running the test suite with "make" and "tox" for different Python …
=> gherkin-python: Remove nose usage with pytest as  test-framework (step 2)

.templates/php/default.mk, gherkin/php/default.mk, messages/php/default.mk
The `default` target was missing in the `pre-release` target for php projects.
That led into messages not being regenerated when trying to pre-release 18.0.0, and tests not being executed after the dependencies have been upgraded.
=> Add default in the php pre-release default makefiles

gherkin/php/Makefile, gherkin/php/composer.json, messages/php/scripts/update-gherkin-dependency.php
When messages 18.0.0 was released, the constraint in gherkin/php/composer.json was changed to `dev-main||^17.0,^18.0`. This is incorrect because `,` is AND. It should have been `dev-main||^17.0||^18.0`
Pre-release of gherkin 23.0.0 removed the `dev-main` and left it as `^17.0,^18.0`. Despite visual inspection by me this was approved and released. It is currently uninstallable as a result.
This removes the script that got rid of 'dev-main', fixes the constraint by removing `^17.0` as there is no php tag for that, and updates the messages script that adds new versions. Fixing this will require a `23.0.1` tag :/
The other issue was builds on main failing. This is because the local 'path repository' that makes gherkin install messages from local filesystem is unable to tell what version the …
=> Fix PHP Gherkin->Messages dependency

compatibility-kit/CHANGELOG.md, compatibility-kit/javascript/features/hooks/hooks.feature, compatibility-kit/ruby/features/hooks/hooks.feature.rb, json-formatter/ruby-testdata/Gemfile
About to release cucumber-ruby 8.0.0.
After upgrading all the gems, cucumber-ruby does not pass the CCK due to missing named hooks support.
It is actually pretty easy to add, so, let's add it in the CCK first, then on cucumber-ruby.
Here, we just need to add a name to the "Before" hook in the ruby step definitions
=> CCK: Add implementation of named hook in ruby

gherkin/perl/t/020_parser_instantiation.t, gherkin/perl/t/data/background.feature
With the testdata removed from the directory of each implementation,
the Perl testsuite was adapted to reference outside of the Perl directory
to access a test file. This strategy doesn't work when a dist has been
created and the dist is running its tests outside of the development
tree.
Instead, copy a single simple test file (which needs to be valid, but
doesn't need to be inline with the rest of the testsuite: we're not
using the results, only the success value) into the test tree.
=> [Perl] Fix out-of-tree tests

messages/php/scripts/update-gherkin-dependency.php
This was incorrectly appending `||` to the dependency list on minor release
=> Gherkin PHP - fix post-release script

gherkin/CHANGELOG.md, gherkin/php/composer.json
Updated `composer.json` to require at least v19 of cubumber PHP messages
When using v24 with lowest dependencies:
```
cucumber/gherkin                      v24.0.0     Gherkin parser
cucumber/messages                     v18.0.0     JSON schema-based messages for Cucumber's inter-process communication
```
We get the following error:
```
PHP Fatal error:  Uncaught Error: Class "Cucumber\Messages\Step\KeywordType" not found in /home/daniel/www/dantleech/gherkin-lint/vendor/cucumber/gherkin/src/GherkinParser.php:38
```
With v19.0.0 of cucumber/messages it works.
=> PHP Gherkin Parser: v24 is not compatible with v18 of messages

gherkin/javascript/Makefile
The Makefile tried to use `npx gherkin` to execute gherkin using
gherkin-streams. Actually the [gherkin-streams bin entrypoint is
named `gherkin-javascript`](https://github.com/cucumber/gherkin-streams/blob/main/package.json#L8).
=> [JavaScript] Fix the gherkin build

gherkin/java/pom.xml, gherkin/java/src/test/java/io/cucumber/gherkin/GherkinDialectProviderTest.java, gherkin/java/src/test/java/io/cucumber/gherkin/GherkinDocumentBuilderTest.java, gherkin/java/src/test/java/io/cucumber/gherkin/GherkinLineTest.java, gherkin/java/src/test/java/io/cucumber/gherkin/GherkinParserTest.java, gherkin/java/src/test/java/io/cucumber/gherkin/MessageVersionTest.java, gherkin/java/src/test/java/io/cucumber/gherkin/ParserTest.java
=> gherkin/java: Upgrade to JUnit 5

gherkin/CHANGELOG.md, gherkin/javascript/src/pickles/compile.ts
=> gherkin/javascript: Include tags from rules in scenario outlines
